/*
 * Copyright (C) 2008-2013 TrinityCore <http://www.trinitycore.org/>
 * Copyright (C) 2005-2009 MaNGOS <http://getmangos.com/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/// \addtogroup u2w
/// @{
/// \file

#ifndef _OPCODES_H
#define _OPCODES_H

#include "Common.h"

/// List of Opcodes
enum Opcodes
{
    NUM_OPCODE_HANDLERS                               = (0x7FFF+1),
    UNKNOWN_OPCODE                                    = (0xFFFF+1),
    NULL_OPCODE                                       = 0,
    COMPRESSED_OPCODE_MASK                            = 0x8000,

    CMSG_ACCEPT_LEVEL_GRANT                           = 0x0, 
    CMSG_ACCEPT_TRADE                                 = 0x1501,
    CMSG_ACTIVATETAXI                                 = 0x1B6E, //5.4.0
    CMSG_ACTIVATETAXIEXPRESS                          = 0x176E, //5.4.0
    CMSG_ADDON_REGISTERED_PREFIXES                    = 0x0, 
    CMSG_ADD_FRIEND                                   = 0x16BD, //5.4.0
    CMSG_ADD_IGNORE                                   = 0x1224, //5.4.0
    CMSG_ADD_VOICE_IGNORE                             = 0x0, 
    CMSG_ALTER_APPEARANCE                             = 0x0, 
    CMSG_AREATRIGGER                                  = 0x1907, //5.4.0
    CMSG_AREA_SPIRIT_HEALER_QUERY                     = 0x0, 
    CMSG_AREA_SPIRIT_HEALER_QUEUE                     = 0x0, 
    CMSG_ARENA_TEAM_ACCEPT                            = 0x0, 
    CMSG_ARENA_TEAM_CREATE                            = 0x0, 
    CMSG_ARENA_TEAM_DECLINE                           = 0x0, 
    CMSG_ARENA_TEAM_DISBAND                           = 0x0, 
    CMSG_ARENA_TEAM_INVITE                            = 0x0, 
    CMSG_ARENA_TEAM_LEADER                            = 0x0, 
    CMSG_ARENA_TEAM_LEAVE                             = 0x0, 
    CMSG_ARENA_TEAM_QUERY                             = 0x0, 
    CMSG_ARENA_TEAM_REMOVE                            = 0x0, 
    CMSG_ARENA_TEAM_ROSTER                            = 0x0, 
    CMSG_ATTACKSTOP                                   = 0x118E, //5.4.0
    CMSG_ATTACKSWING                                  = 0x14AF, //5.4.0 
    CMSG_AUCTION_LIST_BIDDER_ITEMS                    = 0x13E6, //5.4.0
    CMSG_AUCTION_LIST_ITEMS                           = 0x13A2, //5.4.0
    CMSG_AUCTION_LIST_OWNER_ITEMS                     = 0x1272, //5.4.0
    CMSG_AUCTION_LIST_PENDING_SALES                   = 0x0, //0x133A, //5.4.0
    CMSG_AUCTION_PLACE_BID                            = 0x1677, //5.4.0
    CMSG_AUCTION_REMOVE_ITEM                          = 0x17A6, //5.4.0
    CMSG_AUCTION_SELL_ITEM                            = 0x1AEB, //5.4.0
    CMSG_AUTH_SESSION                                 = 0x0790, //5.4.0
    CMSG_AUTOBANK_ITEM                                = 0x0164, //5.4.0
    CMSG_AUTOEQUIP_GROUND_ITEM                        = 0x0,
    CMSG_AUTOEQUIP_ITEM                               = 0x0564, //5.4.0
    CMSG_AUTOEQUIP_ITEM_SLOT                          = 0x0, 
    CMSG_AUTOSTORE_BAG_ITEM                           = 0x0863, 
    CMSG_AUTOSTORE_BANK_ITEM                          = 0x0465, //5.4.0
    CMSG_AUTOSTORE_GROUND_ITEM                        = 0x0,
    CMSG_AUTOSTORE_LOOT_ITEM                          = 0x11AF, //5.4.0
    CMSG_AUTO_DECLINE_GUILD_INVITES                   = 0x1AEF, 
    CMSG_BANKER_ACTIVATE                              = 0x166F, 
    CMSG_BATTLEFIELD_JOIN                             = 0x0,
    CMSG_BATTLEFIELD_LEAVE                            = 0x0, 
    CMSG_BATTLEFIELD_LIST                             = 0x0, 
    CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE        = 0x0, 
    CMSG_BATTLEFIELD_MGR_EXIT_REQUEST                 = 0x0, 
    CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE        = 0x0, 
    CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST                = 0x0, 
    CMSG_BATTLEFIELD_PORT                             = 0x0, 
    CMSG_BATTLEFIELD_REQUEST_SCORE_DATA               = 0x0,
    CMSG_BATTLEFIELD_STATUS                           = 0x0,
    CMSG_BATTLEGROUND_PLAYER_POSITIONS                = 0x0,
    CMSG_BATTLEMASTER_HELLO                           = 0x0,
    CMSG_BATTLEMASTER_JOIN                            = 0x133E,
    CMSG_BATTLEMASTER_JOIN_ARENA                      = 0x0, 
    CMSG_BATTLEMASTER_JOIN_RATED                      = 0x0, 
    CMSG_BEGIN_TRADE                                  = 0x1806,
	CMSG_BLACK_MARKET_BID							  = 0x0,
	CMSG_BLACK_MARKET_HELLO							  = 0x0,
	CMSG_BLACK_MARKET_REQUEST_ITEMS					  = 0x0,
    CMSG_BINDER_ACTIVATE                              = 0x1AE2, //5.4.0
    CMSG_BOT_DETECTED2                                = 0x0,
    CMSG_BUG                                          = 0x0, 
    CMSG_BUSY_TRADE                                   = 0x0, 
    CMSG_BUYBACK_ITEM                                 = 0x16FE, //5.4.0
    CMSG_BUY_BANK_SLOT                                = 0x13A3, //5.4.0
    CMSG_BUY_ITEM                                     = 0x1663, //5.4.0
    CMSG_CALENDAR_ADD_EVENT                           = 0x168B,
    CMSG_CALENDAR_ARENA_TEAM                          = 0x0, 
    CMSG_CALENDAR_COMPLAIN                            = 0x0,
    CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP                = 0x0,
    CMSG_CALENDAR_COPY_EVENT                          = 0x0,
    CMSG_CALENDAR_EVENT_INVITE                        = 0x1703,
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS              = 0x0, 
    CMSG_CALENDAR_EVENT_REMOVE_INVITE                 = 0x0, 
    CMSG_CALENDAR_EVENT_RSVP                          = 0x0, 
    CMSG_CALENDAR_EVENT_SIGNUP                        = 0x0, 
    CMSG_CALENDAR_EVENT_STATUS                        = 0x0, 
    CMSG_CALENDAR_GET_CALENDAR                        = 0x1B8F,
    CMSG_CALENDAR_GET_EVENT                           = 0x0, 
    CMSG_CALENDAR_GET_NUM_PENDING                     = 0x0, 
    CMSG_CALENDAR_GUILD_FILTER                        = 0x0, 
    CMSG_CALENDAR_REMOVE_EVENT                        = 0x0, 
    CMSG_CALENDAR_UPDATE_EVENT                        = 0x0,
    CMSG_CANCEL_AURA                                  = 0x140E, //5.4.0
    CMSG_CANCEL_AUTO_REPEAT_SPELL                     = 0x0, //0x12FB
    CMSG_CANCEL_CAST                                  = 0x0, //0x1524
    CMSG_CANCEL_CHANNELLING                           = 0x0, //0x150E
    CMSG_CANCEL_GROWTH_AURA                           = 0x0,
    CMSG_CANCEL_MOUNT_AURA                            = 0x14AA, //5.4.0
    CMSG_CANCEL_QUEUED_SPELL                          = 0x0, 
    CMSG_CANCEL_TEMP_ENCHANTMENT                      = 0x0, 
    CMSG_CANCEL_TRADE                                 = 0x1807, //5.4.0
    CMSG_CAST_SPELL                                   = 0x1429, //5.4.0
    CMSG_CHANGEPLAYER_DIFFICULTY                      = 0x0, 
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE           = 0x0,
    CMSG_CHANNEL_ANNOUNCEMENTS                        = 0x1517, //5.4.0
    CMSG_CHANNEL_BAN                                  = 0x0, 
    CMSG_CHANNEL_DISPLAY_LIST                         = 0x15BA, //5.4.0
    CMSG_CHANNEL_INVITE                               = 0x11B2, //5.4.0
    CMSG_CHANNEL_KICK                                 = 0x111E, //5.4.0
    CMSG_CHANNEL_LIST                                 = 0x191A, //5.4.0
    CMSG_CHANNEL_MODERATE                             = 0x0,
    CMSG_CHANNEL_MODERATOR                            = 0x0, 
    CMSG_CHANNEL_MUTE                                 = 0x1510, //5.4.0 
    CMSG_CHANNEL_OWNER                                = 0x0, //0x18AE, //5.4.0
    CMSG_CHANNEL_PASSWORD                             = 0x0, 
    CMSG_CHANNEL_ROSTER_INFO                          = 0x0,
    CMSG_CHANNEL_SET_OWNER                            = 0x1435, //5.4.0
    CMSG_CHANNEL_SILENCE_ALL                          = 0x18BF, //5.4.0
    CMSG_CHANNEL_SILENCE_VOICE                        = 0x1095, //5.4.0
    CMSG_CHANNEL_UNBAN                                = 0x141B, //5.4.0
    CMSG_CHANNEL_UNMODERATOR                          = 0x153C, //5.4.0
    CMSG_CHANNEL_UNMUTE                               = 0x1597, //5.4.0
    CMSG_CHANNEL_UNSILENCE_ALL                        = 0x119D, //5.4.0
    CMSG_CHANNEL_UNSILENCE_VOICE                      = 0x14BA, //5.4.0
    CMSG_CHANNEL_VOICE_OFF                            = 0x1538, //5.4.0
    CMSG_CHANNEL_VOICE_ON                             = 0x1415, //5.4.0
    CMSG_CHAR_CREATE                                  = 0x17CF, //5.4.0
    CMSG_CHAR_CUSTOMIZE                               = 0x0, 
    CMSG_CHAR_DELETE                                  = 0x1783, //5.4.0
    CMSG_CHAR_ENUM                                    = 0x1B9E, //5.4.0
    CMSG_CHAR_FACTION_CHANGE                          = 0x0, 
    CMSG_CHAR_RACE_CHANGE                             = 0x0, 
    CMSG_CHAR_RENAME                                  = 0x0, 
    CMSG_CHAT_FILTERED                                = 0x0,
    CMSG_CHAT_IGNORED                                 = 0x0, 
    CMSG_CLEAR_CHANNEL_WATCH                          = 0x0, 
    CMSG_CLEAR_RAID_MARKER                            = 0x0,
    CMSG_CLEAR_TRADE_ITEM                             = 0x1500,
    CMSG_COMMENTATOR_ENABLE                           = 0x0,
    CMSG_COMMENTATOR_ENTER_INSTANCE                   = 0x0, 
    CMSG_COMMENTATOR_EXIT_INSTANCE                    = 0x0, 
    CMSG_COMMENTATOR_GET_MAP_INFO                     = 0x0, 
    CMSG_COMMENTATOR_GET_PARTY_INFO                   = 0x0, 
    CMSG_COMMENTATOR_GET_PLAYER_INFO                  = 0x0,
    CMSG_COMMENTATOR_INSTANCE_COMMAND                 = 0x0,
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND           = 0x0,
    CMSG_COMMENTATOR_START_WARGAME                    = 0x0, 
    CMSG_COMPLAIN                                     = 0x0, 
    CMSG_COMPLETE_CINEMATIC                           = 0x12F8, //5.4.0
    CMSG_COMPLETE_MOVIE                               = 0x132A, //5.4.0
    CMSG_CONNECT_TO_FAILED                            = 0x0, 
    CMSG_CONTACT_LIST                                 = 0x1351, //5.4.0
    CMSG_CORPSE_MAP_POSITION_QUERY                    = 0x0313, //5.4.0
	CMSG_CORPSE_QUERY                                 = 0x13DB, //5.4.0
    CMSG_CREATURE_QUERY                               = 0x1585, //5.4.0
    CMSG_DANCE_QUERY                                  = 0x0, 
    CMSG_DB_QUERY                                     = 0x1A8B, //5.4.0
    CMSG_DECLINE_CHANNEL_INVITE                       = 0x1C16, //5.4.0
    CMSG_DELETEEQUIPMENT_SET                          = 0x0, 
    CMSG_DEL_FRIEND                                   = 0x1AD8, //5.4.0
    CMSG_DEL_IGNORE                                   = 0x1604, //5.4.0
    CMSG_DEL_VOICE_IGNORE                             = 0x0, 
    CMSG_DESTROY_ITEM                                 = 0x1401, //5.4.0
    CMSG_DISMISS_CONTROLLED_VEHICLE                   = 0x072A, //5.4.0
    CMSG_DISMISS_CRITTER                              = 0x0, 
    CMSG_DUEL_ACCEPTED                                = 0x13FE, //5.4.0
    CMSG_DUEL_CANCELLED                               = 0x0, 
	CMSG_DUEL_REQUEST                                 = 0x129B, //5.4.0
    CMSG_DUNGEON_FINDER_GET_SYSTEM_INFO               = 0x0, 
    CMSG_EJECT_PASSENGER                              = 0x0, 
    CMSG_EMOTE                                        = 0x1689, //5.4.0
    CMSG_ENABLETAXI                                   = 0x1AA2, //5.4.0
    CMSG_ENABLE_NAGLE                                 = 0x6999, 
    CMSG_EQUIPMENT_SET_DELETE                         = 0x0, //0x16B6
    CMSG_EQUIPMENT_SET_SAVE                           = 0x0, //0x127A
    CMSG_EQUIPMENT_SET_USE                            = 0x0, //0x0064
    CMSG_FAR_SIGHT                                    = 0x0, 
    CMSG_FORCE_MOVE_ROOT_ACK                          = 0x0,
    CMSG_FORCE_MOVE_UNROOT_ACK                        = 0x0,
    CMSG_GAMEOBJECT_QUERY                             = 0x15A4, //5.4.0
    CMSG_GAMEOBJ_REPORT_USE                           = 0x1B36, //5.4.0
    CMSG_GAMEOBJ_USE                                  = 0x1367, //5.4.0
    CMSG_GAMESPEED_SET                                = 0x0,
    CMSG_GAMETIME_SET                                 = 0x0,
    CMSG_GETDEATHBINDZONE                             = 0x0,
    CMSG_GET_MAIL_LIST                                = 0x1ABB, //5.4.0 
    CMSG_GET_MIRRORIMAGE_DATA                         = 0x0,
    CMSG_GHOST                                        = 0x0,
    CMSG_GMRESPONSE_RESOLVE                           = 0x0, 
    CMSG_GMSURVEY_SUBMIT                              = 0x0, 
    CMSG_GMTICKET_CREATE                              = 0x0, 
    CMSG_GMTICKET_DELETETICKET                        = 0x0, 
    CMSG_GMTICKET_GETTICKET                           = 0x0, 
    CMSG_GMTICKET_SYSTEMSTATUS                        = 0x0, 
    CMSG_GMTICKET_UPDATETEXT                          = 0x0, 
    CMSG_GM_INVIS                                     = 0x0,
    CMSG_GM_NUKE                                      = 0x0,
    CMSG_GM_REPORT_LAG                                = 0x0, 
    CMSG_GM_SET_SECURITY_GROUP                        = 0x0,
    CMSG_GOSSIP_HELLO                                 = 0x1A3F, //5.4.0
    CMSG_GOSSIP_SELECT_OPTION                         = 0x136B, //5.4.0
    CMSG_GRANT_LEVEL                                  = 0x0, 
    CMSG_GROUP_ASSISTANT_LEADER                       = 0x12C2, //5.4.0
    CMSG_GROUP_CANCEL                                 = 0x0,
    CMSG_GROUP_CHANGE_SUB_GROUP                       = 0x1357, //5.4.0
    CMSG_GROUP_DISBAND                                = 0x165E, //5.4.0
    CMSG_GROUP_INVITE                                 = 0x121E, //5.4.0
    CMSG_GROUP_INVITE_RESPONSE                        = 0x1B0A, //5.4.0
    CMSG_GROUP_RAID_CONVERT                           = 0x161B, //5.4.0
    CMSG_GROUP_REQUEST_JOIN_UPDATES                   = 0x0, //0x139B
    CMSG_GROUP_SET_LEADER                             = 0x17DF, //5.4.0
    CMSG_GROUP_SET_ROLES                              = 0x1AC7, //5.4.0
    CMSG_GROUP_SWAP_SUB_GROUP                         = 0x1B56, //5.4.0
    CMSG_GROUP_UNINVITE                               = 0x0,
    CMSG_GROUP_UNINVITE_GUID                          = 0x1BCF, //5.4.0
    CMSG_GUILD_ACCEPT                                 = 0x0, 
    CMSG_GUILD_ACHIEVEMENT_MEMBERS                    = 0x0,
    CMSG_GUILD_ACHIEVEMENT_PROGRESS_QUERY             = 0x0,
    CMSG_GUILD_ADD_RANK                               = 0x0A19, //5.4.0
    CMSG_GUILD_ASSIGN_MEMBER_RANK                     = 0x0, 
    CMSG_GUILD_BANKER_ACTIVATE                        = 0x1776, //5.4.0
    CMSG_GUILD_BANK_BUY_TAB                           = 0x1A67, //5.4.0
    CMSG_GUILD_BANK_DEPOSIT_MONEY                     = 0x1726, //5.4.0
    CMSG_GUILD_BANK_LOG_QUERY                         = 0x032C, //5.4.0
    CMSG_GUILD_BANK_MONEY_WITHDRAWN_QUERY             = 0x0,
    CMSG_GUILD_BANK_NOTE                              = 0x0,
    CMSG_GUILD_BANK_TAB_INFO                          = 0x0, 
    CMSG_GUILD_BANK_QUERY_TAB                         = 0x17BB, //5.4.0
    CMSG_GUILD_BANK_QUERY_TEXT                        = 0x0251, //5.4.0
    CMSG_GUILD_BANK_SWAP_ITEMS                        = 0x0, 
    CMSG_GUILD_BANK_UPDATE_TAB                        = 0x173F, //5.4.0
    CMSG_GUILD_BANK_WITHDRAW_MONEY                    = 0x0,
    CMSG_GUILD_CHANGE_NAME_REQUEST                    = 0x0310, //5.4.0
    CMSG_GUILD_DECLINE                                = 0x0, 
    CMSG_GUILD_DEL_RANK                               = 0x0A35, //5.4.0
    CMSG_GUILD_DEMOTE                                 = 0x0A55, //5.4.0
    CMSG_GUILD_DISBAND                                = 0x0334, //5.4.0
    CMSG_GUILD_EVENT_LOG_QUERY                        = 0x0238, //5.4.0
    CMSG_GUILD_INFO                                   = 0x0,
    CMSG_GUILD_INFO_TEXT                              = 0x0248, //5.4.0
    CMSG_GUILD_INVITE                                 = 0x1B1A, //5.4.0
    CMSG_GUILD_LEAVE                                  = 0x0338, //5.4.0
    CMSG_GUILD_MEMBER_SEND_SOR_REQUEST                = 0x0, 
    CMSG_GUILD_MOTD                                   = 0x024C, //5.4.0
    CMSG_GUILD_NEWS_UPDATE_STICKY                     = 0x033D, //5.4.0
    CMSG_GUILD_PERMISSIONS                            = 0x0,
    CMSG_GUILD_PROMOTE                                = 0x0B0D, //5.4.0
    CMSG_GUILD_QUERY                                  = 0x17C3, //5.4.0
    CMSG_GUILD_QUERY_NEWS                             = 0x0350, //5.4.0
    CMSG_GUILD_QUERY_RANKS                            = 0x0A1D, //5.4.0
    CMSG_GUILD_REMOVE                                 = 0x0B0C, //5.4.0
    CMSG_GUILD_REPLACE_GUILD_MASTER                   = 0x0A15, //5.4.0
    CMSG_GUILD_REQUEST_CHALLENGE_UPDATE               = 0x0,
    CMSG_GUILD_REQUEST_MAX_DAILY_XP                   = 0x0, 
    CMSG_GUILD_REQUEST_PARTY_STATE                    = 0x1885, //5.4.0
    CMSG_GUILD_ROSTER                                 = 0x0315, //5.4.0 Check in IDA again
    CMSG_GUILD_SET_ACHIEVEMENT_TRACKING               = 0x0, 
    CMSG_GUILD_SET_GUILD_MASTER                       = 0x1316, //5.4.0
    CMSG_GUILD_SET_NOTE                               = 0x0369, //5.4.0
    CMSG_GUILD_SET_RANK_PERMISSIONS                   = 0x0, 
    CMSG_GUILD_SWITCH_RANK                            = 0x0, 
    CMSG_HEARTH_AND_RESURRECT                         = 0x0, 
    CMSG_IGNORE_TRADE                                 = 0x1089,
    CMSG_INITIATE_TRADE                               = 0x108E,
    CMSG_INSPECT                                      = 0x167E,
    CMSG_INSPECT_HONOR_STATS                          = 0x14AC,
    CMSG_INSTANCE_LOCK_WARNING_RESPONSE               = 0x0, 
    CMSG_ITEM_REFUND                                  = 0x0, 
    CMSG_ITEM_REFUND_INFO                             = 0x0,
    CMSG_ITEM_TEXT_QUERY                              = 0x1F58, //5.4.0
    CMSG_JOIN_CHANNEL                                 = 0x1C14, //5.4.0 
    CMSG_KEEP_ALIVE                                   = 0x131A, //5.4.0
    CMSG_LEARN_PREVIEW_TALENTS                        = 0x0,
    CMSG_LEARN_PREVIEW_TALENTS_PET                    = 0x0,
    CMSG_LEARN_TALENT                                 = 0x1901, //5.4.0
    CMSG_LEAVE_CHANNEL                                = 0x1131, //5.4.0 
    CMSG_LFG_GET_PLAYER_INFO                          = 0x0,
    CMSG_LFG_GET_STATUS                               = 0x0,
    CMSG_LFG_JOIN                                     = 0x1B57, //5.4.0 
    CMSG_LFG_LEAVE                                    = 0x17C6, //5.4.0
    CMSG_LFG_LFR_JOIN                                 = 0x0,
    CMSG_LFG_LFR_LEAVE                                = 0x0, 
    CMSG_LFG_PARTY_LOCK_INFO_REQUEST                  = 0x1A13, //5.4.0
    CMSG_LFG_PROPOSAL_RESULT                          = 0x1A07, //5.4.0 
    CMSG_LFG_SET_BOOT_VOTE                            = 0x0, 
    CMSG_LFG_SET_COMMENT                              = 0x0, 
    CMSG_LFG_SET_ROLES                                = 0x1A1E, //5.4.0
    CMSG_LFG_TELEPORT                                 = 0x0, 
    CMSG_LF_GUILD_ADD_RECRUIT                         = 0x0, 
    CMSG_LF_GUILD_BROWSE                              = 0x0, 
    CMSG_LF_GUILD_DECLINE_RECRUIT                     = 0x0, 
    CMSG_LF_GUILD_GET_APPLICATIONS                    = 0x0, 
    CMSG_LF_GUILD_GET_RECRUITS                        = 0x0, 
    CMSG_LF_GUILD_POST_REQUEST                        = 0x0, 
    CMSG_LF_GUILD_REMOVE_RECRUIT                      = 0x0, 
    CMSG_LF_GUILD_SET_GUILD_POST                      = 0x0, 
    CMSG_LIST_INVENTORY                               = 0x1762, //5.4.0
    CMSG_LOAD_SCREEN                                  = 0x160B, //5.4.0
    CMSG_LOGOUT_CANCEL                                = 0x1B62, //5.4.0
    CMSG_LOGOUT_REQUEST                               = 0x16E7, //5.4.0
    CMSG_LOG_DISCONNECT                               = 0x0380, //5.4.0
    CMSG_LOOT                                         = 0x18AF, //5.4.0
    CMSG_LOOT_CURRENCY                                = 0x0, 
    CMSG_LOOT_MASTER_GIVE                             = 0x0,
    CMSG_LOOT_METHOD                                  = 0x0, //0x1352
    CMSG_LOOT_MONEY                                   = 0x1080, //5.4.0
    CMSG_LOOT_RELEASE                                 = 0x1022, //5.4.0
    CMSG_LOOT_ROLL                                    = 0x0, 
    CMSG_MAIL_CREATE_TEXT_ITEM                        = 0x1B2A, //5.4.0
    CMSG_MAIL_DELETE                                  = 0x1083, //5.4.0
    CMSG_MAIL_MARK_AS_READ                            = 0x17F2, //5.4.0
    CMSG_MAIL_RETURN_TO_SENDER                        = 0x1486, //5.4.0
    CMSG_MAIL_TAKE_ITEM                               = 0x1B37, //5.4.0
    CMSG_MAIL_TAKE_MONEY                              = 0x16EE, //5.4.0
    CMSG_MEETINGSTONE_INFO                            = 0x0,
    CMSG_MESSAGECHAT_ADDON_BATTLEGROUND               = 0x0, 
    CMSG_MESSAGECHAT_ADDON_GUILD                      = 0x149A, //5.4.0
    CMSG_MESSAGECHAT_ADDON_OFFICER                    = 0x1990, //5.4.0
    CMSG_MESSAGECHAT_ADDON_PARTY                      = 0x0, 
    CMSG_MESSAGECHAT_ADDON_RAID                       = 0x0, 
    CMSG_MESSAGECHAT_ADDON_WHISPER                    = 0x1532, //5.4.0
    CMSG_MESSAGECHAT_AFK                              = 0x15B9, //5.4.0
    CMSG_MESSAGECHAT_BATTLEGROUND                     = 0x0, 
    CMSG_MESSAGECHAT_CHANNEL                          = 0x1134, //5.4.0
    CMSG_MESSAGECHAT_DND                              = 0x19BB, //5.4.0
    CMSG_MESSAGECHAT_EMOTE                            = 0x1C1F, //5.4.0
    CMSG_MESSAGECHAT_GUILD                            = 0x109F, //5.4.0
    CMSG_MESSAGECHAT_OFFICER                          = 0x159C, //5.4.0
    CMSG_MESSAGECHAT_PARTY                            = 0x15B0, //5.4.0
    CMSG_MESSAGECHAT_RAID                             = 0x7009, 
    CMSG_MESSAGECHAT_RAID_WARNING                     = 0x7010, 
    CMSG_MESSAGECHAT_SAY                              = 0x10BE, //5.4.0
    CMSG_MESSAGECHAT_WHISPER                          = 0x19B6, //5.4.0
    CMSG_MESSAGECHAT_YELL                             = 0x1015, //5.4.0 
    CMSG_MINIGAME_MOVE                                = 0x0,
    CMSG_MOUNTSPECIAL_ANIM                            = 0x0, 
    CMSG_MOVE_CHARM_TELEPORT_CHEAT                    = 0x0,
    CMSG_MOVE_CHNG_TRANSPORT                          = 0x0B0E, //5.4.0
    CMSG_MOVE_ENABLE_SWIM_TO_FLY_TRANS_ACK            = 0x0,
    CMSG_MOVE_FALL_RESET                              = 0x0, 
    CMSG_MOVE_FEATHER_FALL_ACK                        = 0x0, 
    CMSG_MOVE_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK      = 0x0,
    CMSG_MOVE_FORCE_FLIGHT_SPEED_CHANGE_ACK           = 0x0, 
    CMSG_MOVE_FORCE_PITCH_RATE_CHANGE_ACK             = 0x0,
    CMSG_MOVE_FORCE_RUN_BACK_SPEED_CHANGE_ACK         = 0x0,
    CMSG_MOVE_FORCE_RUN_SPEED_CHANGE_ACK              = 0x0, 
    CMSG_MOVE_FORCE_SWIM_BACK_SPEED_CHANGE_ACK        = 0x0, 
    CMSG_MOVE_FORCE_SWIM_SPEED_CHANGE_ACK             = 0x0, 
    CMSG_MOVE_FORCE_TURN_RATE_CHANGE_ACK              = 0x0,
    CMSG_MOVE_FORCE_WALK_SPEED_CHANGE_ACK             = 0x0, 
    CMSG_MOVE_GRAVITY_DISABLE_ACK                     = 0x0,
    CMSG_MOVE_GRAVITY_ENABLE_ACK                      = 0x0,
    CMSG_MOVE_HOVER_ACK                               = 0x0, 
    CMSG_MOVE_KNOCK_BACK_ACK                          = 0x0,
    CMSG_MOVE_NOT_ACTIVE_MOVER                        = 0x7003, 
    CMSG_MOVE_SET_CAN_FLY                             = 0x063E, //5.4.0
    CMSG_MOVE_SET_CAN_FLY_ACK                         = 0x0,
    CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK = 0x0,
    CMSG_MOVE_SET_COLLISION_HEIGHT_ACK                = 0x0,
    CMSG_MOVE_SET_RELATIVE_POSITION                   = 0x0,
    CMSG_MOVE_SET_VEHICLE_REC_ID_ACK                  = 0x0,
    CMSG_MOVE_SPLINE_DONE                             = 0x023A, //5.4.0
    CMSG_MOVE_TIME_SKIPPED                            = 0x0,
    CMSG_MOVE_TOGGLE_COLLISION_ACK                    = 0x0,
    CMSG_MOVE_WATER_WALK_ACK                          = 0x0,
    CMSG_NAME_QUERY                                   = 0x16DB, //5.4.0
    CMSG_REALM_CACHE                                  = 0x13D7, //5.4.0
    SMSG_REALM_CACHE                                  = 0x042B, //5.4.0
    CMSG_NEW_SPELL_SLOT                               = 0x0,
    CMSG_NEXT_CINEMATIC_CAMERA                        = 0x0, 
    CMSG_NPC_TEXT_QUERY                               = 0x108B, //5.4.0
    CMSG_OBJECT_UPDATE_FAILED                         = 0x1926, //5.4.0
    CMSG_OBJECT_UPDATE_RESCUED                        = 0x1526, //5.4.0
    CMSG_OFFER_PETITION                               = 0x170B, //5.4.0
    CMSG_OPENING_CINEMATIC                            = 0x0, //Dont use this fucking opcode! but its 0x17C4
    CMSG_OPEN_ITEM                                    = 0x0, 
    CMSG_OPT_OUT_OF_LOOT                              = 0x1277, 
    CMSG_PAGE_TEXT_QUERY                              = 0x1082, //5.4.0
    CMSG_PARTY_SILENCE                                = 0x0,
    CMSG_PARTY_UNSILENCE                              = 0x0,
    CMSG_PETITION_BUY                                 = 0x13AE, //5.4.0
    CMSG_PETITION_QUERY                               = 0x1404, //5.4.0
    CMSG_PETITION_SHOWLIST                            = 0x0, 
    CMSG_PETITION_SHOW_SIGNATURES                     = 0x1B72, //5.4.0
    CMSG_PETITION_SIGN                                = 0x17F3, //5.4.0
    CMSG_PET_ABANDON                                  = 0x0, 
    CMSG_PET_ACTION                                   = 0x0, 
    CMSG_PET_CANCEL_AURA                              = 0x0, 
    CMSG_PET_CAST_SPELL                               = 0x0, 
    CMSG_PET_LEARN_TALENT                             = 0x0, 
    CMSG_PET_NAME_CACHE                               = 0x0,
    CMSG_PET_NAME_QUERY                               = 0x1428, //5.4.0
    CMSG_PET_RENAME                                   = 0x0, 
    CMSG_PET_SET_ACTION                               = 0x0,
    CMSG_PET_SPELL_AUTOCAST                           = 0x04C9,//16257
    CMSG_PET_STOP_ATTACK                              = 0x0, 
    CMSG_PING                                         = 0x0784, //5.4.0
    CMSG_PLAYED_TIME                                  = 0x10AA, //5.4.0
    CMSG_PLAYER_DIFFICULTY_CHANGE                     = 0x0,
    CMSG_PLAYER_LOGIN                                 = 0x1BC7, //5.4.0
    CMSG_PLAYER_LOGOUT                                = 0x0, 
    CMSG_PLAYER_VEHICLE_ENTER                         = 0x0,
    CMSG_PLAY_DANCE                                   = 0x0, 
    CMSG_PUSHQUESTTOPARTY                             = 0x0, 
    CMSG_PVP_LOG_DATA                                 = 0x0, 
    CMSG_QUERY_BATTLEFIELD_STATE                      = 0x0,
    CMSG_QUERY_GUILD_MEMBERS_FOR_RECIPE               = 0x0,
    CMSG_QUERY_GUILD_MEMBER_RECIPES                   = 0x0,
    CMSG_QUERY_GUILD_RECIPES                          = 0x0A6C, //5.4.0
    CMSG_QUERY_GUILD_REWARDS                          = 0x1402, //5.4.0
    CMSG_QUERY_GUILD_XP                               = 0x0250, //5.4.0
    CMSG_QUERY_INSPECT_ACHIEVEMENTS                   = 0x0, //0x1B22
    CMSG_QUERY_QUESTS_COMPLETED                       = 0x0,
    CMSG_QUERY_TIME                                   = 0x0, 
    CMSG_QUERY_WORLD_COUNTDOWN_TIMER                  = 0x0,
    CMSG_QUESTGIVER_ACCEPT_QUEST                      = 0x12B6, //5.4.0
    CMSG_QUESTGIVER_CANCEL                            = 0x0,
    CMSG_QUESTGIVER_CHOOSE_REWARD                     = 0x1A37, //5.4.0
    CMSG_QUESTGIVER_COMPLETE_QUEST                    = 0x1AB3, //5.4.0
    CMSG_QUESTGIVER_HELLO                             = 0x163F, //5.4.0
    CMSG_QUESTGIVER_QUERY_QUEST                       = 0x1377, //5.4.0
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH                  = 0x0,
    CMSG_QUESTGIVER_REQUEST_REWARD                    = 0x1223, //5.4.0
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY             = 0x132F, //5.4.0
    CMSG_QUESTGIVER_STATUS_QUERY                      = 0x17AE, //5.4.0
    CMSG_QUESTLOG_REMOVE_QUEST                        = 0x17AF, //5.4.0
    CMSG_QUESTLOG_SWAP_QUEST                          = 0x0,
    CMSG_QUEST_CONFIRM_ACCEPT                         = 0x1B19, //5.4.0
    CMSG_QUEST_NPC_QUERY                              = 0x0, 
    CMSG_QUEST_POI_QUERY                              = 0x1084, //5.4.0
    CMSG_QUEST_QUERY                                  = 0x1507, //5.4.0
	CMSG_RANDOM_ROLL                                  = 0x1A9B,
    CMSG_RANDOMIZE_CHAR_NAME                          = 0x164B, //5.4.0
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES                 = 0x1A0E, //5.4.0
    CMSG_READ_ITEM                                    = 0x1A95, //5.4.0
    CMSG_REALM_QUERY                                  = 0x0, // Not used since u guys switched the name for no known reason??
    CMSG_REALM_SPLIT                                  = 0x129F, //5.4.0
    CMSG_RECLAIM_CORPSE                               = 0x1AAB, //5.4.0
    CMSG_REDIRECTION_AUTH_PROOF                       = 0x0A93, //5.4.0
    CMSG_REFORGE_ITEM                                 = 0x0, 
    CMSG_REORDER_CHARACTERS                           = 0x171F, //5.4.0
    CMSG_REPAIR_ITEM                                  = 0x1B7B, //5.4.0
    CMSG_REPLACE_ACCOUNT_DATA                         = 0x0,
    CMSG_REPOP_REQUEST                                = 0x163A, //5.4.0
    CMSG_REPORT_PVP_AFK                               = 0x0,
    CMSG_REQUEST_ACCOUNT_DATA                         = 0x0, 
    CMSG_REQUEST_CATEGORY_COOLDOWNS                   = 0x0, 
    CMSG_REQUEST_CEMETERY_LIST                        = 0x0,
    CMSG_REQUEST_HOTFIX                               = 0x0, //0x1A8B
    CMSG_REQUEST_INSPECT_RATED_BG_STATS               = 0x0, //0x1757
    CMSG_REQUEST_PARTY_MEMBER_STATS                   = 0x16CF,
    CMSG_REQUEST_PET_INFO                             = 0x0, 
    CMSG_REQUEST_PVP_OPTIONS_ENABLED                  = 0x0, 
    CMSG_REQUEST_PVP_REWARDS                          = 0x0,
    CMSG_REQUEST_RAID_INFO                            = 0x1612, //5.4.0
    CMSG_REQUEST_RATED_BG_INFO                        = 0x0, //0x1A1E
    CMSG_REQUEST_RATED_BG_STATS                       = 0x0,
    CMSG_REQUEST_RESEARCH_HISTORY                     = 0x0,
    CMSG_REQUEST_VEHICLE_EXIT                         = 0x0, 
    CMSG_REQUEST_VEHICLE_NEXT_SEAT                    = 0x0,
    CMSG_REQUEST_VEHICLE_PREV_SEAT                    = 0x0,
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT                  = 0x0,
    CMSG_RESET_FACTION_CHEAT                          = 0x0,
    CMSG_RESET_INSTANCES                              = 0x1383, 
    CMSG_RESURRECT_RESPONSE                           = 0x0, 
    CMSG_RETURN_TO_GRAVEYARD                          = 0x122A, //5.4.0
    CMSG_ROLE_POLL_BEGIN                              = 0x0, 
    CMSG_SAVE_CUF_PROFILES                            = 0x0, 
    CMSG_SAVE_PLAYER                                  = 0x0,
    CMSG_SEARCH_LFG_JOIN                              = 0x0,
    CMSG_SEARCH_LFG_LEAVE                             = 0x0,
	CMSG_SELECT_FACTION								  = 0x0, 
    CMSG_SELF_RES                                     = 0x0, 
    CMSG_SELL_ITEM                                    = 0x12E7, //5.4.0
    CMSG_SEND_MAIL                                    = 0x1E0E, //5.4.0
    CMSG_SEND_SOR_REQUEST_VIA_ADDRESS                 = 0x0, 
    CMSG_SEND_SOR_REQUEST_VIA_BNET_ACCOUNT_ID         = 0x0, 
    CMSG_SERVERTIME                                   = 0x0,
    CMSG_SETDEATHBINDPOINT                            = 0x0,
    CMSG_SETSHEATHED                                  = 0x17E2, //5.4.0
    CMSG_SET_ACTIONBAR_TOGGLES                        = 0x162B, //5.4.0
    CMSG_SET_ACTION_BUTTON                            = 0x129E, //5.4.0
    CMSG_SET_ACTIVE_MOVER                             = 0x0B23, //5.4.0
    CMSG_SET_ACTIVE_VOICE_CHANNEL                     = 0x0,
    CMSG_SET_ALLOW_LOW_LEVEL_RAID1                    = 0x0, 
    CMSG_SET_ALLOW_LOW_LEVEL_RAID2                    = 0x0,
    CMSG_SET_CHANNEL_WATCH                            = 0x0, 
    CMSG_SET_CONTACT_NOTES                            = 0x1EA4, //5.4.0
    CMSG_SET_CURRENCY_FLAGS                           = 0x0,
    CMSG_SET_EVERYONE_IS_ASSISTANT                    = 0x0, //0x1386
    CMSG_SET_FACTION_ATWAR                            = 0x0, 
    CMSG_SET_FACTION_CHEAT                            = 0x0,
    CMSG_SET_FACTION_INACTIVE                         = 0x0, 
    CMSG_SET_GUILD_BANK_TEXT                          = 0x0,
    CMSG_SET_LFG_COMMENT                              = 0x0,
    CMSG_SET_PET_SLOT                                 = 0x0,
    CMSG_SET_PLAYER_DECLINED_NAMES                    = 0x1BD2, //5.4.0
    CMSG_SET_PREFERED_CEMETERY                        = 0x0,
    CMSG_SET_PRIMARY_TALENT_TREE                      = 0x0,
    CMSG_SET_RELATIVE_POSITION                        = 0x0, 
    CMSG_SET_SAVED_INSTANCE_EXTEND                    = 0x0, 
    CMSG_SET_SELECTION                                = 0x1B76, //5.4.0
    CMSG_SET_SPECIALIZATION                           = 0x1104, //5.4.0
    CMSG_SET_SKILL_CHEAT                              = 0x0,
    CMSG_SET_TAXI_BENCHMARK_MODE                      = 0x0, 
    CMSG_SET_TITLE                                    = 0x11A6, //5.4.0
    CMSG_SET_TRADE_CURRENCY                           = 0x0,
    CMSG_SET_TRADE_GOLD                               = 0x0, //0x1187
    CMSG_SET_TRADE_ITEM                               = 0x0, //0x1425
    CMSG_SET_VEHICLE_REC_ID_ACK                       = 0x0,
    CMSG_SET_WATCHED_FACTION                          = 0x0, 
    CMSG_SHOWING_CLOAK                                = 0x16EA, 
    CMSG_SHOWING_HELM                                 = 0x1A7B, 
    CMSG_SOCKET_GEMS                                  = 0x1B77, //5.4.0
    CMSG_SPELLCLICK                                   = 0x1676, //5.4.0
    CMSG_SPIRIT_HEALER_ACTIVATE                       = 0x1B6F, //5.4.0
    CMSG_SPLIT_ITEM                                   = 0x0, //0x161
    CMSG_STANDSTATECHANGE                             = 0x1181, //5.4.0
    CMSG_START_QUEST                                  = 0x0,
    CMSG_STOP_DANCE                                   = 0x0, 
    CMSG_STORE_LOOT_IN_SLOT                           = 0x0,
    CMSG_SUBMIT_BUG                                   = 0x0, 
    CMSG_SUBMIT_COMPLAIN                              = 0x0, 
    CMSG_SUGGESTION_SUBMIT                            = 0x0,
    CMSG_SUMMON_RESPONSE                              = 0x0, 
    CMSG_SUSPEND_TOKEN                                = 0x0286, //5.4.0
    CMSG_SWAP_INV_ITEM                                = 0x0445, //5.4.0 
    CMSG_SWAP_ITEM                                    = 0x0440, //5.4.0
    CMSG_SYNC_DANCE                                   = 0x0,
    CMSG_TAXICLEARALLNODES                            = 0x0,
    CMSG_TAXIENABLEALLNODES                           = 0x0,
    CMSG_TAXINODE_STATUS_QUERY                        = 0x0, 
    CMSG_TAXIQUERYAVAILABLENODES                      = 0x0, 
    CMSG_TAXISHOWNODES                                = 0x0,
    CMSG_TELEPORT_TO_UNIT                             = 0x0, 
    CMSG_TEXT_EMOTE                                   = 0x1723, //5.4.0 
    CMSG_TIME_ADJUSTMENT_RESPONSE                     = 0x0,
    CMSG_TIME_SYNC_RESP                               = 0x0784, //5.4.0
    CMSG_TIME_SYNC_RESP_FAILED                        = 0x0,
    CMSG_TOGGLE_PVP                                   = 0x182C, //5.4.0
    CMSG_TOTEM_DESTROYED                              = 0x13E3, //5.4.0
    CMSG_TRAINER_BUY_SPELL                            = 0x12EF, //5.4.0
    CMSG_TRAINER_LIST                                 = 0x1AFA, //5.4.0
    CMSG_TRANSMOGRIFY_ITEMS                           = 0x0, 
    CMSG_TRIGGER_CINEMATIC_CHEAT                      = 0x0,
    CMSG_TURN_IN_PETITION                             = 0x1363, //5.4.0
    CMSG_TUTORIAL_CLEAR                               = 0x0, 
    CMSG_TUTORIAL_FLAG                                = 0x0, 
    CMSG_TUTORIAL_RESET                               = 0x0, 
    CMSG_UNACCEPT_TRADE                               = 0x0, //0x15A0
    CMSG_UNLEARN_SKILL                                = 0x0, 
    CMSG_UNLEARN_SPECIALIZATION                       = 0x0, 
    CMSG_UNREGISTER_ALL_ADDON_PREFIXES                = 0x0,
    CMSG_UPDATE_ACCOUNT_DATA                          = 0x0, 
    CMSG_UPDATE_MISSILE_TRAJECTORY                    = 0x0,
    CMSG_UPDATE_PROJECTILE_POSITION                   = 0x0,
    CMSG_USED_FOLLOW                                  = 0x1188, //5.4.0
    CMSG_USE_ITEM                                     = 0x14A8, //5.4.0
    CMSG_VIOLENCE_LEVEL                               = 0x1927, //5.4.0
	//CMSG_VIEW_OBJECT								  = 0x17AE,
    CMSG_VOICE_SESSION_ENABLE                         = 0x0, 
    CMSG_VOID_STORAGE_QUERY                           = 0x0, 
    CMSG_VOID_STORAGE_TRANSFER                        = 0x0, 
    CMSG_VOID_STORAGE_UNLOCK                          = 0x0, 
    CMSG_VOID_SWAP_ITEM                               = 0x0, 
    CMSG_WARDEN_DATA                                  = 0x1702, //5.4.0
    CMSG_WARGAME_ACCEPT                               = 0x0, 
    CMSG_WARGAME_START                                = 0x0,
    CMSG_WHO                                          = 0x1E06, //5.4.0
    CMSG_WHOIS                                        = 0x0, 
    CMSG_WORLD_STATE_UI_TIMER_UPDATE                  = 0x1646, //5.4.0
    CMSG_WORLD_TELEPORT                               = 0x0,
    CMSG_WRAP_ITEM                                    = 0x0, 
    CMSG_ZONEUPDATE                                   = 0x0,  

    MSG_AUCTION_HELLO                                 = 0x1627, 
    MSG_CHANNEL_START                                 = 0x0,  
    MSG_CHANNEL_UPDATE                                = 0x0,  
    MSG_GM_BIND_OTHER                                 = 0x0,
    MSG_GM_SHOWLABEL                                  = 0x0,
    MSG_GM_SUMMON                                     = 0x0,
    MSG_INSPECT_ARENA_TEAMS                           = 0x0, 
    MSG_LIST_STABLED_PETS                             = 0x0, 
    CMSG_MINIMAP_PING                                 = 0x1283, //5.4.0
    SMSG_MINIMAP_PONG                                 = 0x0408, //5.4.0
    MSG_MOVE_CHARM_TELEPORT_CHEAT                     = 0x0, 
    MSG_MOVE_FALL_LAND                                = 0x031F, //5.4.0
    MSG_MOVE_GRAVITY_CHNG                             = 0x0,
    MSG_MOVE_HEARTBEAT                                = 0x0717, //5.4.0
    MSG_MOVE_HOVER                                    = 0x0,
    MSG_MOVE_JUMP                                     = 0x0B17, //5.4.0
    MSG_MOVE_SET_ALL_SPEED_CHEAT                      = 0x0,
    MSG_MOVE_SET_COLLISION_HEIGHT                     = 0x0,
    MSG_MOVE_SET_FACING                               = 0x0B3A, //5.4.0
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT                   = 0x0,
    MSG_MOVE_SET_PITCH                                = 0x030F, //5.4.0
    MSG_MOVE_SET_RAW_POSITION_ACK                     = 0x0,
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT                 = 0x0,
    MSG_MOVE_SET_RUN_MODE                             = 0x0A37, //5.4.0
    MSG_MOVE_SET_RUN_SPEED_CHEAT                      = 0x0,
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT                = 0x0,
    MSG_MOVE_SET_SWIM_SPEED_CHEAT                     = 0x0,
    MSG_MOVE_SET_TURN_RATE_CHEAT                      = 0x0,
    MSG_MOVE_SET_WALK_MODE                            = 0x0A3E, //5.4.0
    MSG_MOVE_SET_WALK_SPEED_CHEAT                     = 0x0,
    MSG_MOVE_START_ASCEND                             = 0x061F, //5.4.0
    MSG_MOVE_START_BACKWARD                           = 0x0216, //5.4.0
    MSG_MOVE_START_DESCEND                            = 0x033A, //5.4.0
    MSG_MOVE_START_FORWARD                            = 0x0723, //5.4.0
    MSG_MOVE_START_PITCH_DOWN                         = 0x063A, //5.4.0
    MSG_MOVE_START_PITCH_UP                           = 0x0E0E, //5.4.0
    MSG_MOVE_START_STRAFE_LEFT                        = 0x0312, //5.4.0
    MSG_MOVE_START_STRAFE_RIGHT                       = 0x0722, //5.4.0
    MSG_MOVE_START_SWIM                               = 0x0712, //5.4.0
    MSG_MOVE_START_TURN_LEFT                          = 0x020E, //5.4.0
    MSG_MOVE_START_TURN_RIGHT                         = 0x0A22, //5.4.0
    MSG_MOVE_STOP                                     = 0x0A06, //5.4.0
    MSG_MOVE_STOP_ASCEND                              = 0x0A2F, //5.4.0
    MSG_MOVE_STOP_PITCH                               = 0x0A1B, //5.4.0
    MSG_MOVE_STOP_STRAFE                              = 0x0E0F, //5.4.0
    MSG_MOVE_STOP_SWIM                                = 0x0A1F, //5.4.0
    MSG_MOVE_STOP_TURN                                = 0x060A, //5.4.0
    MSG_MOVE_TELEPORT                                 = 0x1342, //5.4.0
    MSG_MOVE_TELEPORT_ACK                             = 0x0B2E, //5.4.0
    MSG_MOVE_TELEPORT_CHEAT                           = 0x0,  
    MSG_MOVE_TIME_SKIPPED                             = 0x0,  
    MSG_MOVE_TOGGLE_COLLISION_CHEAT                   = 0x030A, //5.4.0
    MSG_MOVE_TOGGLE_FALL_LOGGING                      = 0x0,
    MSG_MOVE_TOGGLE_LOGGING                           = 0x0,
    MSG_MOVE_UPDATE_CAN_FLY                           = 0x0,
    MSG_MOVE_UPDATE_FLIGHT_SPEED                      = 0x0,
    MSG_MOVE_UPDATE_MOUSE                             = 0x0,
    MSG_MOVE_UPDATE_RUN_SPEED                         = 0x0,
    MSG_MOVE_WATER_WALK                               = 0x0,
    MSG_MOVE_WORLDPORT_ACK                            = 0x0336, //5.4.0
    MSG_NOTIFY_PARTY_SQUELCH                          = 0x0,
    MSG_PARTY_ASSIGNMENT                              = 0x0,
    MSG_PETITION_DECLINE                              = 0x0, 
    MSG_PETITION_RENAME                               = 0x1242, //5.4.0
    MSG_QUERY_NEXT_MAIL_TIME                          = 0x1F61, //5.4.0
    MSG_QUEST_PUSH_RESULT                             = 0x0, 
    CMSG_RAID_READY_CHECK                             = 0x1307, //5.4.0
    SMSG_RAID_READY_CHECK_STARTED                     = 0x012D, //5.4.0
    MSG_RAID_READY_CHECK_CONFIRM                      = 0x0529, //5.4.0
    MSG_RAID_READY_CHECK_FINISHED                     = 0x0085, //5.4.0
    MSG_RAID_TARGET_UPDATE                            = 0x597, // 0x1E16, //5.4.0
    MSG_SAVE_GUILD_EMBLEM                             = 0x0, 
    CMSG_SET_DUNGEON_DIFFICULTY                       = 0x1E17, //5.4.0
    SMSG_SET_DUNGEON_DIFFICULTY                       = 0x040C, //5.4.0
    CMSG_SET_RAID_DIFFICULTY                          = 0x1F80, //5.4.0
    SMSG_SET_RAID_DIFFICULTY                          = 0x1F80, //5.4.0
    MSG_START_MOVE_FORWARD                            = 0x0,
    MSG_TABARDVENDOR_ACTIVATE                         = 0x0, 
    CMSG_RESPEC_WIPE_CONFIRM                          = 0x0, 
    SMSG_RESPEC_WIPE_CONFIRM                          = 0x0BF4,
    MSG_VERIFY_CONNECTIVITY                           = 0x4F57, // Always 0x4F57

	// SMSG
    SMSG_ACCOUNT_DATA_TIMES                           = 0x0890, //5.4.0
    SMSG_ACCOUNT_INFO_RESPONSE                        = 0x0899, //5.4.0
    SMSG_ACCOUNT_RESTRICTED_WARNING                   = 0x002D,  
    SMSG_ACHIEVEMENT_DELETED                          = 0x08BF,
    SMSG_ACHIEVEMENT_EARNED                           = 0x05B4, //5.4.0
    SMSG_ACTION_BUTTONS                               = 0x0096, //5.4.0
    SMSG_ACTIVATETAXIREPLY                            = 0x0119, 
    SMSG_ADDON_INFO                                   = 0x0128, //5.4.0
    SMSG_ADD_RUNE_POWER                               = 0x0, 
    SMSG_AI_REACTION                                  = 0x05B1, 
    SMSG_ALL_ACHIEVEMENT_DATA                         = 0x0816, //5.4.0
    SMSG_AREA_SPIRIT_HEALER_TIME                      = 0x110,  
    SMSG_AREA_TRIGGER_DEBUG_PLAYER_INSIDE             = 0x0,
    SMSG_AREA_TRIGGER_DEBUG_SWEEP                     = 0x0,
    SMSG_AREA_TRIGGER_MESSAGE                         = 0x0A2, 
    SMSG_AREA_TRIGGER_MOVEMENT_UPDATE                 = 0x01D,  
    SMSG_AREA_TRIGGER_RESET                           = 0x8B7,
    SMSG_ARENA_ERROR                                  = 0x91C, 
    SMSG_ARENA_UNIT_DESTROYED                         = 0x0,
    SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED              = 0x0, 
    SMSG_ARENA_TEAM_COMMAND_RESULT                    = 0x0,  
    SMSG_ARENA_TEAM_EVENT                             = 0x0, 
    SMSG_ARENA_TEAM_INVITE                            = 0x0, 
    SMSG_ARENA_TEAM_QUERY_RESPONSE                    = 0x0, 
    SMSG_ARENA_TEAM_ROSTER                            = 0x0, 
    SMSG_ARENA_TEAM_STATS                             = 0x0, 
    SMSG_ATTACKERSTATEUPDATE                          = 0x1BC0, //5.4.0
    SMSG_ATTACKSTART                                  = 0x0427, //5.4.0
    SMSG_ATTACKSTOP                                   = 0x050F, //5.4.0
    SMSG_ATTACKSWING_BADFACING                        = 0x0, 
    SMSG_ATTACKSWING_CANT_ATTACK                      = 0x0, 
    SMSG_ATTACKSWING_DEADTARGET                       = 0x0, 
    SMSG_ATTACKSWING_NOTINRANGE                       = 0x0,
	SMSG_AUCTION_HELLO_REPONSE						  = 0x0186,
    SMSG_AUCTION_BIDDER_LIST_RESULT                   = 0x1F3C, //5.4.0
    SMSG_AUCTION_BIDDER_NOTIFICATION                  = 0x0, 
    SMSG_AUCTION_COMMAND_RESULT                       = 0x5BA,
    SMSG_AUCTION_LIST_PENDING_SALES                   = 0x16CD, //5.4.0
    SMSG_AUCTION_LIST_RESULT                          = 0x1B4D, //5.4.0
    SMSG_AUCTION_OWNER_LIST_RESULT                    = 0x1B21, //5.4.0
    SMSG_AUCTION_OWNER_NOTIFICATION                   = 0x02A, 
    SMSG_AUCTION_REMOVED_NOTIFICATION                 = 0x0, 
    SMSG_AURACASTLOG                                  = 0x0,
    SMSG_AURA_POINTS_DEPLETED                         = 0x0,  
    SMSG_AURA_UPDATE                                  = 0x19B3, //5.4.0
    SMSG_AURA_UPDATE_ALL                              = 0x0, //WTF caffeine not like, so i not use :)
    SMSG_AUTH_CHALLENGE                               = 0x016A, //5.4.0
    SMSG_AUTH_RESPONSE                                = 0x090E, //5.4.0
    SMSG_AVAILABLE_VOICE_CHANNEL                      = 0x101, 
    SMSG_AVERAGE_ITEM_LEVEL_INFORM                    = 0x53A,  
    SMSG_BARBER_SHOP_RESULT                           = 0x59D, 
    SMSG_BATTLEFIELD_LIST                             = 0x1B5,  
    SMSG_BATTLEFIELD_MGR_EJECTED                      = 0x528,  
    SMSG_BATTLEFIELD_MGR_EJECT_PENDING                = 0x582,  
    SMSG_BATTLEFIELD_MGR_ENTERED                      = 0x428,  
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE                 = 0x1B9,  
    SMSG_BATTLEFIELD_MGR_EXIT_REQUEST                 = 0x835,  
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE                 = 0x41D,  
    SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE       = 0x035,  
    SMSG_BATTLEFIELD_MGR_STATE_CHANGE                 = 0x02C,  
    SMSG_BATTLEFIELD_PLAYER_POSITIONS                 = 0x838, 
    SMSG_BATTLEFIELD_PORT_DENIED                      = 0x482,  
    SMSG_BATTLEFIELD_RATED_INFO                       = 0x827, 
    SMSG_BATTLEFIELD_STATUS                           = 0x59C, 
    SMSG_BATTLEFIELD_STATUS_QUEUED                    = 0x10D, 
    SMSG_BATTLEFIELD_STATUS_ACTIVE                    = 0x52B,  
    SMSG_BATTLEFIELD_STATUS_NEEDCONFIRMATION          = 0x507,  
    SMSG_BATTLEFIELD_STATUS_WAITFORGROUPS             = 0x814,  
    SMSG_BATTLEFIELD_STATUS_FAILED                    = 0x5B9,  
    SMSG_BATTLEGROUND_INFO_THROTTLED                  = 0x484,  
    SMSG_BATTLEGROUND_PLAYER_JOINED                   = 0x8B2,  
    SMSG_BATTLEGROUND_PLAYER_LEFT                     = 0x822,  
    CMSG_BATTLE_PET_NAME_QUERY                        = 0x0, 
    SMSG_BATTLE_PET_DELETED                           = 0x8AC, 
    SMSG_BATTLE_PET_ERROR                             = 0x491, 
    SMSG_BATTLE_PET_HEALED                            = 0x108, 
    SMSG_BATTLE_PET_JOURNAL                           = 0x5B5, 
    SMSG_BATTLE_PET_JOURNAL_LOCK_ACQUIRED             = 0x1B1, 
    SMSG_BATTLE_PET_JOURNAL_LOCK_DENIED               = 0x107, 
    SMSG_BATTLE_PET_LICENSE_CHANGED                   = 0x103, 
    SMSG_BATTLE_PET_TRAP_LEVEL                        = 0x81C, 
    SMSG_BATTLE_PET_UPDATES                           = 0x192, 
    CMSG_BATTLE_PET_SUMMON                            = 0x0, 
    CMSG_BATTLE_PET_TRAP                              = 0x0, 
    CMSG_BATTLE_PET_RENAME                            = 0x0, 
    CMSG_BATTLE_PET_TOGGLE_FAVORITE                   = 0x0, 
	SMSG_BLACK_MARKET_HELLO                           = 0x4A6,  
    SMSG_BLACK_MARKET_REQUEST_ITEMS_RESULT			  = 0x481,  
    SMSG_BLACK_MARKET_BID_RESULT                      = 0x92C,  
    SMSG_BLACK_MARKET_OUT_BID                         = 0x195,  
    SMSG_BLACK_MARKET_BID_WON                         = 0x5AB,  
    SMSG_BINDER_CONFIRM                               = 0x0894, //5.4.0
    SMSG_BINDPOINTUPDATE                              = 0x0404, //5.4.0
    SMSG_BINDZONEREPLY                                = 0x0,
    SMSG_BREAK_TARGET                                 = 0x423, 
    SMSG_BUY_BANK_SLOT_RESULT                         = 0x0,
    SMSG_BUY_FAILED                                   = 0x01AA, //5.4.0
    SMSG_BUY_ITEM                                     = 0x05A8, //5.4.0
    SMSG_CALENDAR_ACTION_PENDING                      = 0x0,
    SMSG_CALENDAR_ARENA_TEAM                          = 0x0,
    SMSG_CALENDAR_CLEAR_PENDING_ACTION                = 0x0,
    SMSG_CALENDAR_COMMAND_RESULT                      = 0x0, 
    SMSG_CALENDAR_EVENT_INVITE                        = 0x0,
    SMSG_CALENDAR_EVENT_INVITE_ALERT                  = 0x0, 
    SMSG_CALENDAR_EVENT_INVITE_NOTES                  = 0x0,
    SMSG_CALENDAR_EVENT_INVITE_NOTES_ALERT            = 0x0,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED                = 0x0,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT          = 0x0,
    SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT           = 0x0,
    SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT        = 0x0,
    SMSG_CALENDAR_EVENT_REMOVED_ALERT                 = 0x0, 
    SMSG_CALENDAR_EVENT_STATUS                        = 0x0,
    SMSG_CALENDAR_EVENT_UPDATED_ALERT                 = 0x0,
    SMSG_CALENDAR_FILTER_GUILD                        = 0x0,
    SMSG_CALENDAR_RAID_LOCKOUT_ADDED                  = 0x0,
    SMSG_CALENDAR_RAID_LOCKOUT_REMOVED                = 0x0,
    SMSG_CALENDAR_RAID_LOCKOUT_UPDATED                = 0x0,
    SMSG_CALENDAR_SEND_CALENDAR                       = 0x0, 
    SMSG_CALENDAR_SEND_EVENT                          = 0x0, 
    SMSG_CALENDAR_SEND_NUM_PENDING                    = 0x0, 
    SMSG_CALENDAR_UPDATE_INVITE_LIST                  = 0x0,
    SMSG_CAMERA_SHAKE                                 = 0x0, 
    SMSG_CANCEL_AUTO_REPEAT                           = 0x041C, 
    SMSG_CANCEL_COMBAT                                = 0x48E, // Could be 0x059E
    SMSG_CAST_FAILED                                  = 0x0039, //5.4.0
    SMSG_CHANNEL_LIST                                 = 0x1BA5, 
    SMSG_CHANNEL_MEMBER_COUNT                         = 0x0, 
    SMSG_CHANNEL_NOTIFY                               = 0x1760, 
    SMSG_CHARACTER_LOGIN_FAILED                       = 0x0, 
    SMSG_CHAR_CREATE                                  = 0x0914, //5.4.0
    SMSG_CHAR_CUSTOMIZE                               = 0x0,
    SMSG_CHAR_DELETE                                  = 0x0806, //5.4.0
    SMSG_CHAR_ENUM                                    = 0x0193, //5.4.0
    SMSG_CHAR_FACTION_CHANGE                          = 0x0,
    SMSG_CHAR_RENAME                                  = 0x0,
    SMSG_CHAT_IGNORED_ACCOUNT_MUTED                   = 0x0,  
    SMSG_CHAT_NOT_IN_PARTY                            = 0x0,
    SMSG_CHAT_PLAYER_AMBIGUOUS                        = 0x0,
    SMSG_CHAT_PLAYER_NOT_FOUND                        = 0x0,
    SMSG_CHAT_RESTRICTED                              = 0x0,
    SMSG_CHAT_SERVER_DISCONNECTED                     = 0x0,
    SMSG_CHAT_SERVER_RECONNECTED                      = 0x0, 
    SMSG_CHAT_WRONG_FACTION                           = 0x0, 
    SMSG_CHECK_FOR_BOTS                               = 0x0,
    SMSG_CLEAR_BOSS_EMOTES                            = 0x0,  
    SMSG_CLEAR_COOLDOWN                               = 0x05A4,  
    SMSG_CLEAR_COOLDOWNS                              = 0x0,  
    SMSG_CLEAR_FAR_SIGHT_IMMEDIATE                    = 0x0, 
    SMSG_CLEAR_TARGET                                 = 0x0, 
    SMSG_CLIENTCACHE_VERSION                          = 0x0825, //5.4.0
    SMSG_CLIENT_CONTROL_UPDATE                        = 0x0, 
    SMSG_COMBAT_EVENT_FAILED                          = 0x0, 
    SMSG_COMBAT_LOG_MULTIPLE                          = 0x0,
    SMSG_COMMENTATOR_MAP_INFO                         = 0x0,
    SMSG_COMMENTATOR_PARTY_INFO                       = 0x0,  
    SMSG_COMMENTATOR_PLAYER_INFO                      = 0x0,
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1           = 0x0,
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2           = 0x0,
    SMSG_COMMENTATOR_STATE_CHANGED                    = 0x0,
    SMSG_COMPLAIN_RESULT                              = 0x0,
    SMSG_COMPRESSED_ACHIEVEMENT_DATA                  = 0x0,
    SMSG_COMPRESSED_CHAR_ENUM                         = 0x0,
    SMSG_COMPRESSED_GUILD_ROSTER                      = 0x0,
    SMSG_COMPRESSED_MOVES                             = 0x0, 
    SMSG_COMPRESSED_UPDATE_OBJECT                     = 0x0,
    SMSG_COMSAT_CONNECT_FAIL                          = 0x0,
    SMSG_COMSAT_DISCONNECT                            = 0x0,
    SMSG_COMSAT_RECONNECT_TRY                         = 0x0,
    SMSG_CONTACT_LIST                                 = 0x13F5, 
    SMSG_CONVERT_RUNE                                 = 0x0, 
    SMSG_COOLDOWN_CHEAT                               = 0x03C1,  
    SMSG_COOLDOWN_EVENT                               = 0x0185,  
    SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE           = 0x0903, //5.4.0
    SMSG_CORPSE_NOT_IN_INSTANCE                       = 0x0,  
    SMSG_CORPSE_RECLAIM_DELAY                         = 0x04BB,  
	SMSG_CORPSE_QUERY                                 = 0x0903, //5.4.0 
    SMSG_CREATURE_QUERY_RESPONSE                      = 0x01B4, //5.4.0
    SMSG_CRITERIA_DELETED                             = 0x0,
    SMSG_CRITERIA_UPDATE                              = 0x0537, //5.4.0
    SMSG_CROSSED_INEBRIATION_THRESHOLD                = 0x0, 
    SMSG_CURRENCY_LOOT_REMOVED                        = 0x0,  
    SMSG_CURRENCY_LOOT_RESTORED                       = 0x0,
    SMSG_CUSTOM_LOAD_SCREEN                           = 0x0,  
    SMSG_DAMAGE_CALC_LOG                              = 0x0, 
    SMSG_DAMAGE_DONE_OBSOLETE                         = 0x0,
    SMSG_DANCE_QUERY_RESPONSE                         = 0x0, 
    SMSG_DB_REPLY                                     = 0x0025, //5.4.0
    SMSG_DEATH_RELEASE_LOC                            = 0x0885, 
    SMSG_DEBUG_RUNE_REGEN                             = 0x0,  
    SMSG_DEFENSE_MESSAGE                              = 0x0, 
    SMSG_DESTROY_OBJECT                               = 0x04BD, //5.4.0
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE                 = 0x0,
    SMSG_DIFFERENT_INSTANCE_FROM_PARTY                = 0x0,  
    SMSG_DISENCHANT_CREDIT                            = 0x0,  
    SMSG_DISMOUNT                                     = 0x0, 
    SMSG_DISMOUNTRESULT                               = 0x0, 
    SMSG_DISPEL_FAILED                                = 0x0,
    SMSG_DISPLAY_GAME_ERROR                           = 0x0,  
    SMSG_DONT_AUTO_PUSH_SPELLS_TO_ACTION_BAR          = 0x0,  
    SMSG_DROP_NEW_CONNECTION                          = 0x0,  
    SMSG_DUEL_COMPLETE                                = 0x0, 
    SMSG_DUEL_COUNTDOWN                               = 0x0, 
    SMSG_DUEL_INBOUNDS                                = 0x0,
    SMSG_DUEL_OUTOFBOUNDS                             = 0x0,
    SMSG_DUEL_REQUESTED                               = 0x0, 
    SMSG_DUEL_WINNER                                  = 0x0,
    SMSG_DUMP_RIDE_TICKETS_RESPONSE                   = 0x0,  
    SMSG_DURABILITY_DAMAGE_DEATH                      = 0x0, 
    SMSG_ECHO_PARTY_SQUELCH                           = 0x0, 
    SMSG_EMOTE                                        = 0x1B7D, //5.4.0
    SMSG_ENABLE_BARBER_SHOP                           = 0x0, 
    SMSG_ENCHANTMENTLOG                               = 0x0,
    SMSG_ENVIRONMENTALDAMAGELOG                       = 0x0, 
    SMSG_EQUIPMENT_SET_LIST                           = 0x0, 
    SMSG_EQUIPMENT_SET_SAVED                          = 0x0,
    SMSG_EQUIPMENT_SET_USE_RESULT                     = 0x0,
    SMSG_EXPECTED_SPAM_RECORDS                        = 0x0, 
    SMSG_EXPLORATION_EXPERIENCE                       = 0x0583, 
    SMSG_FAILED_PLAYER_CONDITION                      = 0x0524, //5.4.0
    SMSG_FEATURE_SYSTEM_STATUS                        = 0x00B9, //5.4.0
    SMSG_FEIGN_DEATH_RESISTED                         = 0x0, 
    SMSG_FISH_ESCAPED                                 = 0x0, 
    SMSG_FISH_NOT_HOOKED                              = 0x0, 
    SMSG_FLIGHT_SPLINE_SYNC                           = 0x0, 
    SMSG_FLOOD_DETECTED                               = 0x0,  
    SMSG_FORCEACTIONSHOW                              = 0x0,
    SMSG_FORCED_DEATH_UPDATE                          = 0x0,
    SMSG_FORCE_DISPLAY_UPDATE                         = 0x0,
    SMSG_FORCE_SEND_QUEUED_PACKETS                    = 0x0,
    SMSG_FORCE_SET_VEHICLE_REC_ID                     = 0x0, 
    SMSG_FORGE_MASTER_SET                             = 0x0,  
    SMSG_FRIEND_STATUS                                = 0x1B29, 
    SMSG_GAMEOBJECT_CUSTOM_ANIM                       = 0x0,  
    SMSG_GAMEOBJECT_DESPAWN_ANIM                      = 0x0,
    SMSG_GAMEOBJECT_PAGETEXT                          = 0x0,
    SMSG_GAMEOBJECT_QUERY_RESPONSE                    = 0x0015, //5.4.0
    SMSG_GAMEOBJECT_RESET_STATE                       = 0x0,
    SMSG_GAMESPEED_SET                                = 0x0,
    SMSG_GAMETIME_SET                                 = 0x0,
    SMSG_GAMETIME_UPDATE                              = 0x0,
    SMSG_GAME_EVENT_DEBUG_LOG                         = 0x0,  
    SMSG_GAME_OBJECT_ACTIVATE_ANIM_KIT                = 0x0,  
    SMSG_GMRESPONSE_DB_ERROR                          = 0x0, 
    SMSG_GMRESPONSE_RECEIVED                          = 0x0, 
    SMSG_GMRESPONSE_STATUS_UPDATE                     = 0x0, 
    SMSG_GMTICKET_CREATE                              = 0x0, 
    SMSG_GMTICKET_DELETETICKET                        = 0x0, 
    SMSG_GMTICKET_GETTICKET                           = 0x0, 
    SMSG_GMTICKET_SYSTEMSTATUS                        = 0x0, 
    SMSG_GMTICKET_UPDATETEXT                          = 0x0, 
    SMSG_GM_MESSAGECHAT                               = 0x0, 
    SMSG_GM_PLAYER_INFO                               = 0x0, 
    SMSG_GM_TICKET_STATUS_UPDATE                      = 0x0, 
    SMSG_GODMODE                                      = 0x533, 
    SMSG_GOSSIP_COMPLETE                              = 0x153C, 
    SMSG_GOSSIP_MESSAGE                               = 0x1508, 
    SMSG_GOSSIP_POI                                   = 0x1E0C, 
    SMSG_GROUPACTION_THROTTLED                        = 0x429,
    SMSG_GROUP_CANCEL                                 = 0x0, 
    SMSG_GROUP_DECLINE                                = 0x12D1, 
    SMSG_GROUP_DESTROYED                              = 0x1280, 
    SMSG_GROUP_INVITE                                 = 0x01C, 
    SMSG_GROUP_LIST                                   = 0x013D, 
    SMSG_GROUP_SET_LEADER                             = 0x43F, 
    SMSG_GROUP_SET_ROLE                               = 0x088B, 
    SMSG_GROUP_UNINVITE                               = 0x1734, 
    SMSG_GUILD_ACHIEVEMENT_DATA                       = 0x0, 
    SMSG_GUILD_ACHIEVEMENT_DELETED                    = 0x0,  
    SMSG_GUILD_ACHIEVEMENT_EARNED                     = 0x0,  
    SMSG_GUILD_ACHIEVEMENT_MEMBERS                    = 0x0,  
    SMSG_GUILD_BANK_LIST                              = 0x0,  
    SMSG_GUILD_BANK_LOG_QUERY_RESULT                  = 0x0,  
    SMSG_GUILD_BANK_MONEY_WITHDRAWN                   = 0x0,  
    SMSG_GUILD_BANK_QUERY_TEXT_RESULT                 = 0x0,  
    SMSG_GUILD_CANCEL                                 = 0x0,
    SMSG_GUILD_CHALLENGE_COMPLETED                    = 0x0,  
    SMSG_GUILD_CHALLENGE_UPDATED                      = 0x0,  
    SMSG_GUILD_CHANGE_NAME_RESULT                     = 0x0,  
    SMSG_GUILD_COMMAND_RESULT                         = 0x0,  
    SMSG_GUILD_COMMAND_RESULT_2                       = 0x0, 
    SMSG_GUILD_CRITERIA_DATA                          = 0x0,  
    SMSG_GUILD_CRITERIA_DELETED                       = 0x0,  
    SMSG_GUILD_DECLINE                                = 0x18BC,
    SMSG_GUILD_EVENT                                  = 0x0,  
    SMSG_GUILD_EVENT_LOG_QUERY_RESULT                 = 0x046B,  
    SMSG_GUILD_FLAGGED_FOR_RENAME                     = 0x0,  
    SMSG_GUILD_INVITE                                 = 0x0,  
    SMSG_GUILD_INVITE_CANCEL                          = 0x0,
    SMSG_GUILD_KNOWN_RECIPES                          = 0x0,
    SMSG_GUILD_MAX_DAILY_XP                           = 0x0,  
    SMSG_GUILD_MEMBERS_FOR_RECIPE                     = 0x0,  
    SMSG_GUILD_MEMBER_DAILY_RESET                     = 0x0,  
    SMSG_GUILD_MEMBER_RECIPES                         = 0x0,  
    SMSG_GUILD_MEMBER_UPDATE_NOTE                     = 0x0,  
    SMSG_GUILD_MOVE_COMPLETE                          = 0x0,  
    SMSG_GUILD_MOVE_STARTING                          = 0x0,  
    SMSG_GUILD_NEWS_DELETED                           = 0x0,  
    SMSG_GUILD_NEWS_UPDATE                            = 0x054E,  
    SMSG_GUILD_PARTY_STATE_RESPONSE                   = 0x0,  
    SMSG_GUILD_PERMISSIONS_QUERY_RESULTS              = 0x0,  
    SMSG_GUILD_QUERY_RESPONSE                         = 0x0D42, 
    SMSG_GUILD_RANK                                   = 0x0446,  
    SMSG_GUILD_RANKS_UPDATE                           = 0x0, 
    SMSG_GUILD_RECIPES                                = 0x0,  
    SMSG_GUILD_RENAMED                                = 0x0,  
    SMSG_GUILD_REPUTATION_REACTION_CHANGED            = 0x0,  
    SMSG_GUILD_REPUTATION_WEEKLY_CAP                  = 0x0,  
    SMSG_GUILD_RESET                                  = 0x0,  
    SMSG_GUILD_REWARDS_LIST                           = 0x0C5A,  
    SMSG_GUILD_ROSTER                                 = 0x044E,  
    SMSG_GUILD_SET_NOTE                               = 0x0,
    SMSG_GUILD_TRADESKILL_UPDATE                      = 0x0,
    SMSG_GUILD_UPDATE_ROSTER                          = 0x0,  
    SMSG_GUILD_XP                                     = 0x0,  
    SMSG_GUILD_XP_GAIN                                = 0x0,  
    SMSG_GUILD_XP_UPDATE                              = 0x0,
    SMSG_HEALTH_UPDATE                                = 0x0,
    SMSG_HIGHEST_THREAT_UPDATE                        = 0x0, 
    SMSG_HOTFIX_INFO                                  = 0x0416, //5.4.0
    SMSG_HOTFIX_NOTIFY                                = 0x0,  
    SMSG_INITIALIZE_FACTIONS                          = 0x090F, //5.4.0
    SMSG_INITIAL_SPELLS                               = 0x1534, //5.4.0
    SMSG_INIT_CURRENCY                                = 0x0494, //5.4.0
    SMSG_INIT_WORLD_STATES                            = 0x0929, //5.4.0
    SMSG_INSPECT                                      = 0x0,
    SMSG_INSPECT_HONOR_STATS                          = 0x0,  
    SMSG_INSPECT_RATED_BG_STATS                       = 0x0,  
    SMSG_INSPECT_RESULTS_UPDATE                       = 0x0,  
    SMSG_INSPECT_TALENT                               = 0x0,
    SMSG_INSTANCE_DIFFICULTY                          = 0x0,
    SMSG_INSTANCE_LOCK_WARNING_QUERY                  = 0x0,
    SMSG_INSTANCE_RESET                               = 0x0, 
    SMSG_INSTANCE_RESET_FAILED                        = 0x0, 
    SMSG_INSTANCE_SAVE_CREATED                        = 0x0, 
    SMSG_INVALIDATE_DANCE                             = 0x0, 
    SMSG_INVALIDATE_PLAYER                            = 0x0, 
    SMSG_INVALID_PROMOTION_CODE                       = 0x0, 
    SMSG_INVENTORY_CHANGE_FAILURE                     = 0x0, 
    SMSG_ITEM_ADD_PASSIVE                             = 0x0,  
    SMSG_ITEM_COOLDOWN                                = 0x0, 
    SMSG_ITEM_ENCHANT_TIME_UPDATE                     = 0x0, 
    SMSG_ITEM_EXPIRE_PURCHASE_REFUND                  = 0x0,  
    SMSG_ITEM_PUSH_RESULT                             = 0x0,  
    SMSG_ITEM_REFUND_INFO_RESPONSE                    = 0x0,
    SMSG_ITEM_REFUND_RESULT                           = 0x0,  
    SMSG_ITEM_REMOVE_PASSIVE                          = 0x0,  
    SMSG_ITEM_SEND_PASSIVE                            = 0x0,  
    SMSG_ITEM_TEXT_QUERY_RESPONSE                     = 0x0, 
    SMSG_ITEM_TIME_UPDATE                             = 0x0, 
    SMSG_JOINED_BATTLEGROUND_QUEUE                    = 0x0,
    SMSG_KICK_REASON                                  = 0x0,
    SMSG_LEARNED_DANCE_MOVES                          = 0x0, 
    SMSG_LEARNED_SPELL                                = 0x0830, //5.4.0
    SMSG_LEVELUP_INFO                                 = 0x0402, //5.4.0
    SMSG_LFG_BOOT_PROPOSAL_UPDATE                     = 0x0,
    SMSG_LFG_DISABLED                                 = 0x0105,
    SMSG_LFG_JOIN_RESULT                              = 0x0017,  
    SMSG_LFG_OFFER_CONTINUE                           = 0x08AB, 
    SMSG_LFG_OPEN_FROM_GOSSIP                         = 0x0,
    SMSG_LFG_PARTY_INFO                               = 0x0, 
    SMSG_LFG_PLAYER_INFO                              = 0x0, 
    SMSG_LFG_PLAYER_REWARD                            = 0x05A2, 
    SMSG_LFG_PROPOSAL_UPDATE                          = 0x049F,  
    SMSG_LFG_QUEUE_STATUS                             = 0x008D,  
    SMSG_LFG_ROLE_CHECK_UPDATE                        = 0x0, 
    SMSG_LFG_ROLE_CHOSEN                              = 0x0,
    SMSG_LFG_SLOT_INVALID                             = 0x0080,  
    SMSG_LFG_TELEPORT_DENIED                          = 0x0833,  
    SMSG_LFG_UPDATE_LIST                              = 0x0,
    SMSG_LFG_UPDATE_PARTY                             = 0x0,
    SMSG_LFG_UPDATE_PLAYER                            = 0x0,
    SMSG_LFG_UPDATE_SEARCH                            = 0x0,  
    SMSG_LFG_UPDATE_STATUS                            = 0x0807,  
    SMSG_LFG_UPDATE_STATUS_NONE                       = 0x0909,  
    SMSG_LF_GUILD_APPLICANT_LIST_UPDATED              = 0x0,  
    SMSG_LF_GUILD_APPLICATIONS_LIST_CHANGED           = 0x0,  
    SMSG_LF_GUILD_BROWSE_UPDATED                      = 0x0,  
    SMSG_LF_GUILD_COMMAND_RESULT                      = 0x0,  
    SMSG_LF_GUILD_MEMBERSHIP_LIST_UPDATED             = 0x0,
    SMSG_LF_GUILD_POST_UPDATED                        = 0x0,  
    SMSG_LF_GUILD_RECRUIT_LIST_UPDATED                = 0x0,  
    SMSG_LIST_INVENTORY                               = 0x088D, //5.4.0
    SMSG_LOAD_CUF_PROFILES                            = 0x0,  
    SMSG_LOGIN_SETTIMESPEED                           = 0x01AF, //5.4.0
    SMSG_LOGIN_VERIFY_WORLD                           = 0x0896, //5.4.0
    SMSG_LOGOUT_CANCEL_ACK                            = 0x0417, //5.4.0
    SMSG_LOGOUT_COMPLETE                              = 0x00A8, //5.4.0
    SMSG_LOGOUT_RESPONSE                              = 0x08AD, //5.4.0
    SMSG_LOG_XPGAIN                                   = 0x04A2, //5.4.0
    SMSG_LOOT_ALL_PASSED                              = 0x0AB,  
    SMSG_LOOT_CLEAR_MONEY                             = 0x0003,  
    SMSG_LOOT_CONTENTS                                = 0x0,  
    SMSG_LOOT_ITEM_NOTIFY                             = 0x0,
    SMSG_LOOT_LIST                                    = 0x0BB,  
    SMSG_LOOT_MASTER_LIST                             = 0x0,  
    SMSG_LOOT_MONEY_NOTIFY                            = 0x052D, //5.4.0
    SMSG_LOOT_RELEASE_RESPONSE                        = 0x0, 
    SMSG_LOOT_REMOVED                                 = 0x05A6,  
    SMSG_LOOT_RESPONSE                                = 0x048F,  
    SMSG_LOOT_ROLL                                    = 0x526,  
    SMSG_LOOT_ROLL_WON                                = 0x1BD,  
    SMSG_LOOT_SLOT_CHANGED                            = 0x0,
    SMSG_LOOT_START_ROLL                              = 0x510,  
    SMSG_MAIL_LIST_RESULT                             = 0x088C, 
    SMSG_MAP_OBJ_EVENTS                               = 0x0,  
    SMSG_MEETINGSTONE_COMPLETE                        = 0x0,
    SMSG_MEETINGSTONE_IN_PROGRESS                     = 0x0,
    SMSG_MEETINGSTONE_MEMBER_ADDED                    = 0x0,
    SMSG_MEETINGSTONE_SETQUEUE                        = 0x0,
    SMSG_MESSAGECHAT                                  = 0x092F, //5.4.0
    SMSG_MESSAGE_BOX                                  = 0x0,  
    SMSG_MINIGAME_SETUP                               = 0x0, 
    SMSG_MINIGAME_STATE                               = 0x0,
    SMSG_MIRRORIMAGE_DATA                             = 0x0, 
    SMSG_MISSILE_CANCEL                               = 0x0,  
    SMSG_MODIFY_COOLDOWN                              = 0x0,  
    SMSG_MONEY_NOTIFY                                 = 0x0585,  
    SMSG_MONSTER_MOVE                                 = 0x137A, //5.4.0
    SMSG_MONSTER_MOVE_TRANSPORT                       = 0x0, 
    SMSG_MOTD                                         = 0x082A, //5.4.0
    SMSG_MOUNTRESULT                                  = 0x0, 
    SMSG_MOUNTSPECIAL_ANIM                            = 0x0, 
    SMSG_MOVE_COLLISION_DISABLE                       = 0x0,  
    SMSG_MOVE_COLLISION_ENABLE                        = 0x0,  
    //SMSG_MOVE_DISABLE_COLLISION                       = 0x0000,
    //SMSG_MOVE_DISABLE_GRAVITY                         = 0x0000,
    //SMSG_MOVE_ENABLE_COLLISION                        = 0x0000,
    //SMSG_MOVE_ENABLE_GRAVITY                          = 0x0000,
    SMSG_MOVE_FEATHER_FALL                            = 0x0,  
    SMSG_MOVE_GRAVITY_DISABLE                         = 0x0,  
    SMSG_MOVE_GRAVITY_ENABLE                          = 0x0,  
    SMSG_MOVE_KNOCK_BACK                              = 0x16FA, //5.4.0
    SMSG_MOVE_LAND_WALK                               = 0x0,
    SMSG_MOVE_NORMAL_FALL                             = 0x0,  
    SMSG_MOVE_ROOT                                    = 0x130B, //5.4.0
    SMSG_MOVE_SET_ACTIVE_MOVER                        = 0x12E3, //5.4.0
    SMSG_MOVE_SET_CAN_FLY                             = 0x1353, //5.4.0
    SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x0,  
    SMSG_MOVE_SET_COLLISION_HEIGHT                    = 0x0,  
    SMSG_MOVE_SET_COMPOUND_STATE                      = 0x0,  
    SMSG_MOVE_SET_FLIGHT_BACK_SPEED                   = 0x1A2B, //5.4.0 
    SMSG_MOVE_SET_FLIGHT_SPEED                        = 0x179F, //5.4.0
    SMSG_MOVE_SET_HOVER                               = 0x0,  
    SMSG_MOVE_SET_PITCH_RATE                          = 0x1247, //5.4.0 
    SMSG_MOVE_SET_RUN_BACK_SPEED                      = 0x1782, //5.4.0 
    SMSG_MOVE_SET_RUN_SPEED                           = 0x12D6, //5.4.0
    SMSG_MOVE_SET_SWIM_BACK_SPEED                     = 0x13D7, //5.4.0
    SMSG_MOVE_SET_SWIM_SPEED                          = 0x1356, //5.4.0
    SMSG_MOVE_SET_TURN_RATE                           = 0x176B, //5.4.0
    SMSG_MOVE_SET_VEHICLE_REC_ID                      = 0x0,
    SMSG_MOVE_SET_WALK_IN_AIR                         = 0x0,
    SMSG_MOVE_SET_WALK_SPEED                          = 0x0258, //5.4.0 or 0x161B
    SMSG_MOVE_UNROOT                                  = 0x1259, //5.4.0 
    SMSG_MOVE_UNSET_CAN_FLY                           = 0x16CE, //5.4.0
    SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY = 0x0,  
    SMSG_MOVE_UNSET_HOVER                             = 0x0,  
    SMSG_MOVE_UNSET_WALK_IN_AIR                       = 0x0,
    SMSG_MOVE_UPDATE_COLLISION_HEIGHT                 = 0x0,  
    SMSG_MOVE_UPDATE_FLIGHT_BACK_SPEED                = 0x0,  
    SMSG_MOVE_UPDATE_KNOCK_BACK                       = 0x0,  
    SMSG_MOVE_UPDATE_PITCH_RATE                       = 0x0,  
    SMSG_MOVE_UPDATE_RUN_BACK_SPEED                   = 0x0,   
    SMSG_MOVE_UPDATE_RUN_SPEED                        = 0x0,
    SMSG_MOVE_UPDATE_SWIM_BACK_SPEED                  = 0x0,  
    SMSG_MOVE_UPDATE_SWIM_SPEED                       = 0x0,  
    SMSG_MOVE_UPDATE_TELEPORT                         = 0x7006, 
    SMSG_MOVE_UPDATE_TURN_RATE                        = 0x0,  
    SMSG_MOVE_UPDATE_WALK_SPEED                       = 0x0,  
    SMSG_MOVE_WATER_WALK                              = 0x0,  
    SMSG_MULTIPLE_PACKETS                             = 0x0, 
    SMSG_NAME_QUERY_RESPONSE                          = 0x00B7, //5.4.0
    SMSG_NEW_TAXI_PATH                                = 0x0431, 
    SMSG_NEW_WORLD                                    = 0x0896, //5.4.0
    SMSG_NEW_WORLD_ABORT                              = 0x0,  
    SMSG_NEUTRAL_PLAYER_FACTION_SELECT_RESULT         = 0x0,
    SMSG_NOTIFICATION                                 = 0x042E, //5.4.0
    SMSG_NOTIFY_DANCE                                 = 0x0, 
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST                   = 0x0,
    SMSG_NPC_TEXT_UPDATE                              = 0x0886, //5.4.0
    SMSG_NPC_WONT_TALK                                = 0x0,
    SMSG_OFFER_PETITION_ERROR                         = 0x0, 
    SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA         = 0x0,
    SMSG_OPEN_CONTAINER                               = 0x0, 
    SMSG_OPEN_LFG_DUNGEON_FINDER                      = 0x00B3,
    SMSG_OVERRIDE_LIGHT                               = 0x0, 
    SMSG_PAGE_TEXT_QUERY_RESPONSE                     = 0x0, 
    SMSG_PARTYKILLLOG                                 = 0x0,
    SMSG_PARTY_COMMAND_RESULT                         = 0x16A5, 
    SMSG_PARTY_MEMBER_STATS                           = 0x013C, 
    SMSG_PARTY_MEMBER_STATS_FULL                      = 0x0, 
    SMSG_PAUSE_MIRROR_TIMER                           = 0x0488, 
    SMSG_PERIODICAURALOG                              = 0x1097, //5.4.0
    SMSG_PETGODMODE                                   = 0x0, 
    SMSG_PETITION_ALREADY_SIGNED                      = 0x0,  
    SMSG_PETITION_QUERY_RESPONSE                      = 0x0, 
    SMSG_PETITION_SHOWLIST                            = 0x0, 
    SMSG_PETITION_SHOW_SIGNATURES                     = 0x0, 
    SMSG_PETITION_SIGN_RESULTS                        = 0x0, 
    SMSG_PET_ACTION_FEEDBACK                          = 0x0, 
    SMSG_PET_ACTION_SOUND                             = 0x0, 
    SMSG_PET_ADDED                                    = 0x0, 
    SMSG_PET_BROKEN                                   = 0x0,
    SMSG_PET_CAST_FAILED                              = 0x0, 
    SMSG_PET_DISMISS_SOUND                            = 0x0, 
    SMSG_PET_GUIDS                                    = 0x0, 
    SMSG_PET_LEARNED_SPELL                            = 0x0,  
    SMSG_PET_MODE                                     = 0x0, 
    SMSG_PET_NAME_INVALID                             = 0x0,
    SMSG_PET_NAME_QUERY_RESPONSE                      = 0x05A1, 
    SMSG_PET_REMOVED_SPELL                            = 0x0, 
    SMSG_PET_RENAMEABLE                               = 0x0,
    SMSG_PET_SLOT_UPDATED                             = 0x0,  
    SMSG_PET_SPECIALIZATION                           = 0x0,
    SMSG_PET_SPELLS                                   = 0x0, 
    SMSG_PET_TAME_FAILURE                             = 0x0,
    SMSG_PET_UPDATE_COMBO_POINTS                      = 0x0, 
    SMSG_PET_BATTLE_CHAT_RESTRICTED                   = 0x0,
    SMSG_PET_BATTLE_FINAL_ROUND                       = 0x0,
    SMSG_PET_BATTLE_FINALIZE_LOCATION                 = 0x0,
    SMSG_PET_BATTLE_FINISHED                          = 0x0,
    SMSG_PET_BATTLE_FIRST_ROUND                       = 0x0,
    SMSG_PET_BATTLE_FULL_UPDATE                       = 0x0, 
    SMSG_PET_BATTLE_MAX_GAME_LENGTH_WARNING           = 0x0,
    SMSG_PET_BATTLE_PVP_CHALLENGE                     = 0x0, 
    SMSG_PET_BATTLE_QUEUE_PROPOSE_MATCH               = 0x0, 
    SMSG_PET_BATTLE_QUEUE_STATUS                      = 0x0,
    SMSG_PET_BATTLE_REPLACEMENTS_MADE                 = 0x0,
    SMSG_PET_BATTLE_REQUEST_FAILED                    = 0x0,
    SMSG_PET_BATTLE_ROUND_RESULT                      = 0x0,
    SMSG_PLAYED_TIME                                  = 0x0, 
    SMSG_PLAYERBINDERROR                              = 0x0, 
    SMSG_PLAYERBOUND                                  = 0x0808, //5.4.0
    SMSG_PLAYER_DIFFICULTY_CHANGE                     = 0x0,  
    SMSG_PLAYER_MOVE                                  = 0x139F, //5.4.0
    SMSG_PLAYER_SKINNED                               = 0x0,  
    SMSG_PLAYER_UNK_DEAD_ALIVE                        = 0x0,
    SMSG_PLAYER_VEHICLE_DATA                          = 0x0,  
    SMSG_PLAY_DANCE                                   = 0x0,  
    SMSG_PLAY_MUSIC                                   = 0x0,  
    SMSG_PLAY_OBJECT_SOUND                            = 0x0,  
    SMSG_PLAY_ONE_SHOT_ANIM_KIT                       = 0x0,
    SMSG_PLAY_SOUND                                   = 0x0,  
    SMSG_PLAY_SPELL_VISUAL                            = 0x0,  
    SMSG_PLAY_SPELL_VISUAL_KIT                        = 0x01A5,  
    SMSG_PLAY_TIME_WARNING                            = 0x0,  
    SMSG_PONG                                         = 0x0043, //5.4.0
    SMSG_POWER_UPDATE                                 = 0x04AD, //5.4.0
    SMSG_PRE_RESURRECT                                = 0x04AA,  
    SMSG_PROCRESIST                                   = 0x0,
    SMSG_PROPOSE_LEVEL_GRANT                          = 0x0,  
    SMSG_PUREMOUNT_CANCELLED_OBSOLETE                 = 0x0,
    SMSG_PVP_CREDIT                                   = 0x0,
    SMSG_PVP_LOG_DATA                                 = 0x0,  
    SMSG_PVP_OPTIONS_ENABLED                          = 0x0,  
    SMSG_QUERY_QUESTS_COMPLETED_RESPONSE              = 0x0,  
    SMSG_QUERY_TIME_RESPONSE                          = 0x0,  
    SMSG_QUESTGIVER_OFFER_REWARD                      = 0x151F,
    SMSG_QUESTGIVER_QUEST_COMPLETE                    = 0x10BD,  
    SMSG_QUESTGIVER_QUEST_DETAILS                     = 0x142D,  
    SMSG_QUESTGIVER_QUEST_FAILED                      = 0x0,  
    SMSG_QUESTGIVER_QUEST_INVALID                     = 0x0,  
    SMSG_QUESTGIVER_QUEST_LIST                        = 0x0,  
    SMSG_QUESTGIVER_REQUEST_ITEMS                     = 0x199E,  
    SMSG_QUESTGIVER_STATUS                            = 0x0,  
    SMSG_QUESTGIVER_STATUS_MULTIPLE                   = 0x188D,  
    SMSG_QUESTLOG_FULL                                = 0x152A,  
    SMSG_QUESTUPDATE_ADD_ITEM                         = 0x0,
    SMSG_QUESTUPDATE_ADD_KILL                         = 0x1988,  
    SMSG_QUESTUPDATE_ADD_PVP_KILL                     = 0x0,  
    SMSG_QUESTUPDATE_COMPLETE                         = 0x0,  
    SMSG_QUESTUPDATE_FAILED                           = 0x0,
    SMSG_QUESTUPDATE_FAILEDTIMER                      = 0x0,  
    SMSG_QUEST_NPC_QUERY_RESPONSE                     = 0x0,
    SMSG_QUEST_CONFIRM_ACCEPT                         = 0x0,  
    SMSG_QUEST_FORCE_REMOVE                           = 0x0,
    SMSG_QUEST_POI_QUERY_RESPONSE                     = 0x183F,  
    SMSG_QUEST_QUERY_RESPONSE                         = 0x19AB,  
    SMSG_RAID_GROUP_ONLY                              = 0x0,
    SMSG_RAID_INSTANCE_INFO                           = 0x0,  
    SMSG_RAID_INSTANCE_MESSAGE                        = 0x0,  
    SMSG_RAID_MARKERS_CHANGED                         = 0x0,  
    SMSG_RAID_READY_CHECK_THROTTLED_ERROR             = 0x0,
    SMSG_RAID_SUMMON_FAILED                           = 0x0, 
	SMSG_RAID_TARGET_UPDATE_ALL                       = 0x09E,  // 5.4.0
	SMSG_RANDOM_ROLL                                  = 0x821,  
    SMSG_RANDOMIZE_CHAR_NAME                          = 0x08B9, //5.4.0
    SMSG_RATED_BG_RATING                              = 0x0,  
    SMSG_RATED_BG_STATS                               = 0x0,  
    SMSG_READ_ITEM_FAILED                             = 0x0,  
    SMSG_READ_ITEM_OK                                 = 0x1231,  
    SMSG_REALM_QUERY                                  = 0x0000, //5.4.0
    SMSG_REALM_SPLIT                                  = 0x0099, //5.4.0
    SMSG_REAL_GROUP_UPDATE                            = 0x0,
    SMSG_RECEIVED_MAIL                                = 0x0,  
    SMSG_REDIRECT_CLIENT                              = 0x0,  
    SMSG_REFER_A_FRIEND_EXPIRED                       = 0x0,  
    SMSG_REFER_A_FRIEND_FAILURE                       = 0x0, 
    SMSG_REFORGE_RESULT                               = 0x0,  
    SMSG_REMOVED_SPELL                                = 0x0, 
    SMSG_REPORT_PVP_AFK_RESULT                        = 0x0, 
    SMSG_REQUEST_CEMETERY_LIST_RESPONSE               = 0x0,  
    SMSG_REQUEST_PVP_REWARDS_RESPONSE                 = 0x0,  
    SMSG_RESEARCH_COMPLETE                            = 0x0,  
    SMSG_RESEARCH_SETUP_HISTORY                       = 0x0,  
    SMSG_RESET_COMPRESSION_CONTEXT                    = 0x0,  
    SMSG_RESET_FAILED_NOTIFY                          = 0x0,
    SMSG_RESISTLOG                                    = 0x0,
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS                 = 0x0,  
    SMSG_RESURRECT_REQUEST                            = 0x0, 
    SMSG_RESYNC_RUNES                                 = 0x0, 
    SMSG_ROLE_POLL_BEGIN                              = 0x0,  
    SMSG_RWHOIS                                       = 0x0, 
    SMSG_SELL_ITEM                                    = 0x0135, //5.4.0
    SMSG_SEND_MAIL_RESULT                             = 0x0, 
    SMSG_SEND_UNLEARN_SPELLS                          = 0x1116, //5.4.0
    SMSG_SERVERTIME                                   = 0x0,
    SMSG_SERVER_FIRST_ACHIEVEMENT                     = 0x0,  
    SMSG_SERVER_INFO_RESPONSE                         = 0x0,  
    SMSG_SERVER_MESSAGE                               = 0x13A9, //5.4.0
    SMSG_SERVER_PERF                                  = 0x0,  
    SMSG_SET_AI_ANIM_KIT                              = 0x0,
    SMSG_SET_DF_FAST_LAUNCH_RESULT                    = 0x0,  
    SMSG_SET_FACTION_ATWAR                            = 0x0, 
    SMSG_SET_FACTION_STANDING                         = 0x0, 
    SMSG_SET_FACTION_VISIBLE                          = 0x0525, 
    SMSG_SET_FLAT_SPELL_MODIFIER                      = 0x0, 
    SMSG_SET_FORCED_REACTIONS                         = 0x0, 
    SMSG_SET_MELEE_ANIM_KIT                           = 0x0,
    SMSG_SET_MOVEMENT_ANIM_KIT                        = 0x0,
    SMSG_SET_PCT_SPELL_MODIFIER                       = 0x0, 
    SMSG_SET_PHASE_SHIFT                              = 0x0919, //5.4.0
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT             = 0x0,
    SMSG_SET_PLAY_HOVER_ANIM                          = 0x0,  
    SMSG_SET_PROFICIENCY                              = 0x012C, //5.4.0
    SMSG_SET_PROJECTILE_POSITION                      = 0x0,
    SMSG_SHOWTAXINODES                                = 0x0032, 
    SMSG_SHOW_BANK                                    = 0x0005, //5.4.0
    SMSG_SHOW_RATINGS                                 = 0x0, 
    SMSG_SHOW_NEUTRAL_PLAYER_FACTION_SELECT_UI        = 0x0,
	SMSG_SOCKET_GEMS_RESULT							  = 0x011D, //5.4.0
    SMSG_SOR_START_EXPERIENCE_INCOMPLETE              = 0x0,  
    SMSG_SPELLBREAKLOG                                = 0x0,
    SMSG_SPELLDAMAGESHIELD                            = 0x0, 
    SMSG_SPELLDISPELLOG                               = 0x0,
    SMSG_SPELLENERGIZELOG                             = 0x0, 
    SMSG_SPELLHEALLOG                                 = 0x0, 
    SMSG_SPELLINSTAKILLLOG                            = 0x0, 
    SMSG_SPELLINTERRUPTLOG                            = 0x0,  
    SMSG_SPELLLOGEXECUTE                              = 0x0, 
    SMSG_SPELLLOGMISS                                 = 0x0, 
    SMSG_SPELLNONMELEEDAMAGELOG                       = 0x1085, //5.4.0
    SMSG_SPELLORDAMAGE_IMMUNE                         = 0x0, 
    SMSG_SPELLSTEALLOG                                = 0x0,
    SMSG_SPELL_CATEGORY_COOLDOWN                      = 0x0, 
    SMSG_SPELL_COOLDOWN                               = 0x0,
    SMSG_SPELL_DELAYED                                = 0x0,
    SMSG_SPELL_FAILED_OTHER                           = 0x0,
    SMSG_SPELL_FAILURE                                = 0x0, 
    SMSG_SPELL_GO                                     = 0x10B6, //5.4.0
    SMSG_SPELL_START                                  = 0x1C17, //5.4.0
    SMSG_SPELL_UPDATE_CHAIN_TARGETS                   = 0x0,
    SMSG_SPIRIT_HEALER_CONFIRM                        = 0x0923, 
    SMSG_SPLINE_MOVE_COLLISION_DISABLE                = 0x1A23, //5.4.0
    SMSG_SPLINE_MOVE_COLLISION_ENABLE                 = 0x166E, //5.4.0
    SMSG_SPLINE_MOVE_GRAVITY_DISABLE                  = 0x1207, //5.4.0
    SMSG_SPLINE_MOVE_GRAVITY_ENABLE                   = 0x129B, //5.4.0
    SMSG_SPLINE_MOVE_ROOT                             = 0x177B, //5.4.0
    SMSG_SPLINE_MOVE_SET_FEATHER_FALL                 = 0x0, //5.4.0
    SMSG_SPLINE_MOVE_SET_FLIGHT_BACK_SPEED            = 0x16BB, //5.4.0
    SMSG_SPLINE_MOVE_SET_FLIGHT_SPEED                 = 0x160E, //5.4.0
    SMSG_SPLINE_MOVE_SET_FLYING                       = 0x165F, //5.4.0
    SMSG_SPLINE_MOVE_SET_HOVER                        = 0x126A, //5.4.0
    SMSG_SPLINE_MOVE_SET_LAND_WALK                    = 0x137E, //5.4.0
    SMSG_SPLINE_MOVE_SET_NORMAL_FALL                  = 0x1A4B, //5.4.0
    SMSG_SPLINE_MOVE_SET_PITCH_RATE                   = 0x1767, //5.4.0
    SMSG_SPLINE_MOVE_SET_RUN_BACK_SPEED               = 0x174B, //5.4.0
    SMSG_SPLINE_MOVE_SET_RUN_MODE                     = 0x1717, //5.4.0
    SMSG_SPLINE_MOVE_SET_RUN_SPEED                    = 0x16FB, //5.4.0
    SMSG_SPLINE_MOVE_SET_SWIM_BACK_SPEED              = 0x173B, //5.4.0
    SMSG_SPLINE_MOVE_SET_SWIM_SPEED                   = 0x1662, //5.4.0
    SMSG_SPLINE_MOVE_SET_TURN_RATE                    = 0x138A, //5.4.0
    SMSG_SPLINE_MOVE_SET_WALK_MODE                    = 0x1AA3, //5.4.0
    SMSG_SPLINE_MOVE_SET_WALK_SPEED                   = 0x166A, //5.4.0
    SMSG_SPLINE_MOVE_SET_WATER_WALK                   = 0x1386, //5.4.0
    SMSG_SPLINE_MOVE_START_SWIM                       = 0x165B, //5.4.0
    SMSG_SPLINE_MOVE_STOP_SWIM                        = 0x1A5F, //5.4.0
    SMSG_SPLINE_MOVE_UNROOT                           = 0x1AC7, //5.4.0
    SMSG_SPLINE_MOVE_UNSET_FLYING                     = 0x1343, //5.4.0
    SMSG_SPLINE_MOVE_UNSET_HOVER                      = 0x122A, //5.4.0
    SMSG_SPLINE_MOVE_WATER_WALK                       = 0x0,
    SMSG_STABLE_RESULT                                = 0x0, 
    SMSG_STANDSTATE_UPDATE                            = 0x000D, //5.4.0
    SMSG_START_MIRROR_TIMER                           = 0x0434, 
    SMSG_START_TIMER                                  = 0x0,
    SMSG_STOP_DANCE                                   = 0x0, 
    SMSG_STOP_MIRROR_TIMER                            = 0x05AE, 
    SMSG_STREAMING_MOVIE                              = 0x0,  
    SMSG_SUMMON_CANCEL                                = 0x0,
    SMSG_SUMMON_REQUEST                               = 0x0, 
    SMSG_SUPERCEDED_SPELL                             = 0x0117,  
    SMSG_SUPPRESS_NPC_GREETINGS                       = 0x0,  
    SMSG_SUSPEND_COMMS                                = 0x0,  
    SMSG_RESUME_COMMS                                 = 0x0,
    SMSG_SUSPEND_TOKEN_RESPONSE                       = 0x0,  
    SMSG_TALENTS_ERROR                                = 0x0, 
    SMSG_TALENTS_INFO                                 = 0x0924, //5.4.0
    SMSG_TALENTS_INVOLUNTARILY_RESET                  = 0x0, 
    SMSG_TAXINODE_STATUS                              = 0x009F, 
    SMSG_TEST_DROP_RATE_RESULT                        = 0x0,
    SMSG_TEXT_EMOTE                                   = 0x003B, 
    SMSG_THREAT_CLEAR                                 = 0x0917, //5.4.0
    SMSG_THREAT_REMOVE                                = 0x0, 
    SMSG_THREAT_UPDATE                                = 0x0, 
    SMSG_TIME_ADJUSTMENT                              = 0x0,  
    SMSG_TIME_SYNC_REQ                                = 0x08A6, //5.4.0
    SMSG_TITLE_EARNED                                 = 0x0, 
    SMSG_TOGGLE_XP_GAIN                               = 0x0, 
    SMSG_TOTEM_CREATED                                = 0x0, 
    SMSG_TRADE_STATUS                                 = 0x0,  
    SMSG_TRADE_STATUS_EXTENDED                        = 0x0,  
    SMSG_TRAINER_BUY_FAILED                           = 0x0031, 
    SMSG_TRAINER_BUY_SUCCEEDED                        = 0x0,
    SMSG_TRAINER_LIST                                 = 0x009A, 
    SMSG_TRANSFER_ABORTED                             = 0x08A9, 
    SMSG_TRANSFER_PENDING                             = 0x08B5, //5.4.0
    SMSG_TRIGGER_CINEMATIC                            = 0x16AD, //5.4.0
    SMSG_TRIGGER_MOVIE                                = 0x0, 
    SMSG_TURN_IN_PETITION_RESULTS                     = 0x0, 
    SMSG_TUTORIAL_FLAGS                               = 0x1F35, //5.4.0
    SMSG_UNIT_HEALTH_FREQUENT                         = 0x0,
    SMSG_UNIT_SPELLCAST_START                         = 0x0,
    SMSG_UPDATE_ACCOUNT_DATA                          = 0x0, 
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE                 = 0x0, 
    SMSG_UPDATE_COMBO_POINTS                          = 0x0, 
    SMSG_UPDATE_CURRENCY                              = 0x00B4, 
    SMSG_UPDATE_CURRENCY_WEEK_LIMIT                   = 0x0,
    SMSG_UPDATE_DUNGEON_ENCOUNTER_FOR_LOOT            = 0x0,  
    SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT               = 0x0,
    SMSG_UPDATE_INSTANCE_OWNERSHIP                    = 0x0, 
    SMSG_UPDATE_ITEM_ENCHANTMENTS                     = 0x0, 
    SMSG_UPDATE_LAST_INSTANCE                         = 0x0, 
    SMSG_UPDATE_OBJECT                                = 0x17D9, //5.4.0
    SMSG_UPDATE_SERVER_PLAYER_POSITION                = 0x0, 
    SMSG_UPDATE_WORLD_STATE                           = 0x090D, //5.4.0
    SMSG_USERLIST_ADD                                 = 0x0, 
    SMSG_USERLIST_REMOVE                              = 0x0, 
    SMSG_USERLIST_UPDATE                              = 0x0, 
    SMSG_VOICESESSION_FULL                            = 0x0,
    SMSG_VOICE_CHAT_STATUS                            = 0x0, 
    SMSG_VOICE_PARENTAL_CONTROLS                      = 0x0, 
    SMSG_VOICE_SESSION_LEAVE                          = 0x0, 
    SMSG_VOICE_SESSION_ROSTER_UPDATE                  = 0x0, 
    SMSG_VOICE_SET_TALKER_MUTED                       = 0x0, 
    SMSG_VOID_ITEM_SWAP_RESPONSE                      = 0x0,  
    SMSG_VOID_STORAGE_CONTENTS                        = 0x0,  
    SMSG_VOID_STORAGE_FAILED                          = 0x0,  
    SMSG_VOID_STORAGE_TRANSFER_CHANGES                = 0x0,  
    SMSG_VOID_TRANSFER_RESULT                         = 0x0,  
    SMSG_WAIT_QUEUE_FINISH                            = 0x51D,  
    SMSG_WAIT_QUEUE_UPDATE                            = 0x129,  
    SMSG_WARDEN_DATA                                  = 0x002,  
    SMSG_WARGAME_CHECK_ENTRY                          = 0x937, 
    SMSG_WARGAME_REQUEST_SENT                         = 0x503,  
    SMSG_WEATHER                                      = 0x04A7, //5.4.0
    SMSG_WEEKLY_LAST_RESET                            = 0x11A, 
    SMSG_WEEKLY_RESET_CURRENCY                        = 0x0,  
    SMSG_WEEKLY_SPELL_USAGE                           = 0x0,  
    SMSG_WEEKLY_SPELL_USAGE_UPDATE                    = 0x0,  
    SMSG_WHO                                          = 0x08A5, 
    SMSG_WHOIS                                        = 0x49D, 
    SMSG_WORLD_SERVER_INFO                            = 0x052E, //5.4.0
    SMSG_WORLD_STATE_UI_TIMER_UPDATE                  = 0x0911, //5.4.0
    SMSG_XP_GAIN_ABORTED                              = 0x131,  
    SMSG_ZONE_UNDER_ATTACK                            = 0x0, 
    SMSG_SET_TIME_ZONE                                = 0x0883, //5.4.0
};

/// Player state
enum SessionStatus
{
    STATUS_AUTHED = 0,                                      // Player authenticated (_player == NULL, m_playerRecentlyLogout = false or will be reset before handler call, m_GUID have garbage)
    STATUS_LOGGEDIN,                                        // Player in game (_player != NULL, m_GUID == _player->GetGUID(), inWorld())
    STATUS_TRANSFER,                                        // Player transferring to another map (_player != NULL, m_GUID == _player->GetGUID(), !inWorld())
    STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,                    // _player != NULL or _player == NULL && m_playerRecentlyLogout && m_playerLogout, m_GUID store last _player guid)
    STATUS_NEVER,                                           // Opcode not accepted from client (deprecated or server side only)
    STATUS_UNHANDLED                                        // Opcode not handled yet
};

enum PacketProcessing
{
    PROCESS_INPLACE = 0,                                    //process packet whenever we receive it - mostly for non-handled or non-implemented packets
    PROCESS_THREADUNSAFE,                                   //packet is not thread-safe - process it in World::UpdateSessions()
    PROCESS_THREADSAFE                                      //packet is thread-safe - process it in Map::Update()
};

class WorldPacket;
class WorldSession;

typedef void(WorldSession::*pOpcodeHandler)(WorldPacket& recvPacket);

struct OpcodeHandler
{
    OpcodeHandler() {}
    OpcodeHandler(char const* _name, SessionStatus _status, PacketProcessing _processing, pOpcodeHandler _handler)
        : Name(_name), Status(_status), ProcessingPlace(_processing), Handler(_handler) {}

    char const* Name;
    SessionStatus Status;
    PacketProcessing ProcessingPlace;
    pOpcodeHandler Handler;
};

class OpcodeTable
{
    public:
        OpcodeTable()
        {
            memset(_internalTable, 0, sizeof(_internalTable));
        }

        ~OpcodeTable()
        {
            for (uint16 i = 0; i < NUM_OPCODE_HANDLERS; ++i)
                delete _internalTable[i];
        }

        void Initialize();

        OpcodeHandler const* operator[](uint32 index) const
        {
            return _internalTable[index];
        }

    private:
        template<bool isInValidRange>
        void ValidateAndSetOpcode(uint16 opcode, char const* name, SessionStatus status, PacketProcessing processing, pOpcodeHandler handler);

        // Prevent copying this structure
        OpcodeTable(OpcodeTable const&);
        OpcodeTable& operator=(OpcodeTable const&);

        OpcodeHandler* _internalTable[NUM_OPCODE_HANDLERS];
};

extern OpcodeTable opcodeTable;

void InitOpcodes();

/// Lookup opcode name for human understandable logging
inline std::string GetOpcodeNameForLogging(Opcodes id)
{
    uint32 opcode = id;
    std::ostringstream ss;
    ss << '[';

    if (id < UNKNOWN_OPCODE)
    {
        if (OpcodeHandler const* handler = opcodeTable[uint32(id) & 0x7FFF])
        {
            ss << handler->Name;
            if (opcode & COMPRESSED_OPCODE_MASK)
                ss << "_COMPRESSED";
        }
        else
            ss << "UNKNOWN OPCODE";
    }
    else
        ss << "INVALID OPCODE";

    ss << " 0x" << std::hex << std::uppercase << opcode << std::nouppercase << " (" << std::dec << opcode << ")]";
    return ss.str();
}
#endif
/// @}